// lessonsLazy.ts — TỆP SINH TỰ ĐỘNG, ĐỪNG SỬA TAY.
// Sinh bởi `npm run gen:stem-lesson-index` (scripts/gen-stem-lesson-index.ts).
// Thêm hoặc sửa bài học xong PHẢI chạy lại lệnh đó, nếu không chỉ mục lệch với nội dung thật.
import type { StemLessonSummary } from '@dhcb/core-contracts/stemLesson'
import type { MathLesson } from './lessonTypes.js'

export const LESSON_INDEX: StemLessonSummary[] = [
  {
    id: 'toan6-c1-b1',
    grade: '6',
    chapterNumber: 1,
    chapterTitle: 'Tập hợp các số tự nhiên',
    lessonNumber: 1,
    title: 'Tập hợp và cách ghi số tự nhiên',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c1',
  },
  {
    id: 'toan6-c1-b2',
    grade: '6',
    chapterNumber: 1,
    chapterTitle: 'Tập hợp các số tự nhiên',
    lessonNumber: 2,
    title: 'Phép cộng, phép trừ, phép nhân và phép chia số tự nhiên',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c1',
  },
  {
    id: 'toan6-c1-b3',
    grade: '6',
    chapterNumber: 1,
    chapterTitle: 'Tập hợp các số tự nhiên',
    lessonNumber: 3,
    title: 'Luỹ thừa với số mũ tự nhiên và thứ tự thực hiện phép tính',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c1',
  },
  {
    id: 'toan6-c2-b1',
    grade: '6',
    chapterNumber: 2,
    chapterTitle: 'Tính chia hết trong tập hợp các số tự nhiên',
    lessonNumber: 1,
    title: 'Quan hệ chia hết và các dấu hiệu chia hết cho 2, 3, 5, 9',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c2',
  },
  {
    id: 'toan6-c2-b2',
    grade: '6',
    chapterNumber: 2,
    chapterTitle: 'Tính chia hết trong tập hợp các số tự nhiên',
    lessonNumber: 2,
    title: 'Số nguyên tố và phân tích một số ra thừa số nguyên tố',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c2',
  },
  {
    id: 'toan6-c2-b3',
    grade: '6',
    chapterNumber: 2,
    chapterTitle: 'Tính chia hết trong tập hợp các số tự nhiên',
    lessonNumber: 3,
    title: 'Ước chung lớn nhất và bội chung nhỏ nhất',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c2',
  },
  {
    id: 'toan6-c3-b1',
    grade: '6',
    chapterNumber: 3,
    chapterTitle: 'Số nguyên',
    lessonNumber: 1,
    title: 'Tập hợp các số nguyên và thứ tự trên trục số',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c3',
  },
  {
    id: 'toan6-c3-b2',
    grade: '6',
    chapterNumber: 3,
    chapterTitle: 'Số nguyên',
    lessonNumber: 2,
    title: 'Phép cộng, phép trừ số nguyên và quy tắc dấu ngoặc',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c3',
  },
  {
    id: 'toan6-c3-b3',
    grade: '6',
    chapterNumber: 3,
    chapterTitle: 'Số nguyên',
    lessonNumber: 3,
    title: 'Phép nhân, phép chia hết, ước và bội của số nguyên',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c3',
  },
  {
    id: 'toan6-c4-b1',
    grade: '6',
    chapterNumber: 4,
    chapterTitle: 'Một số hình phẳng trong thực tiễn',
    lessonNumber: 1,
    title: 'Tam giác đều, hình vuông và lục giác đều',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c4',
  },
  {
    id: 'toan6-c4-b2',
    grade: '6',
    chapterNumber: 4,
    chapterTitle: 'Một số hình phẳng trong thực tiễn',
    lessonNumber: 2,
    title: 'Hình chữ nhật, hình thoi, hình bình hành và hình thang cân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c4',
  },
  {
    id: 'toan6-c4-b3',
    grade: '6',
    chapterNumber: 4,
    chapterTitle: 'Một số hình phẳng trong thực tiễn',
    lessonNumber: 3,
    title: 'Chu vi và diện tích của một số hình trong thực tiễn',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c4',
  },
  {
    id: 'toan6-c5-b1',
    grade: '6',
    chapterNumber: 5,
    chapterTitle: 'Tính đối xứng của hình phẳng trong tự nhiên',
    lessonNumber: 1,
    title: 'Hình có trục đối xứng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c5',
  },
  {
    id: 'toan6-c5-b2',
    grade: '6',
    chapterNumber: 5,
    chapterTitle: 'Tính đối xứng của hình phẳng trong tự nhiên',
    lessonNumber: 2,
    title: 'Hình có tâm đối xứng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c5',
  },
  {
    id: 'toan6-c6-b1',
    grade: '6',
    chapterNumber: 6,
    chapterTitle: 'Phân số',
    lessonNumber: 1,
    title: 'Mở rộng phân số và phân số bằng nhau',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c6',
  },
  {
    id: 'toan6-c6-b2',
    grade: '6',
    chapterNumber: 6,
    chapterTitle: 'Phân số',
    lessonNumber: 2,
    title: 'So sánh phân số và hỗn số dương',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c6',
  },
  {
    id: 'toan6-c6-b3',
    grade: '6',
    chapterNumber: 6,
    chapterTitle: 'Phân số',
    lessonNumber: 3,
    title: 'Phép tính với phân số và hai bài toán về phân số',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c6',
  },
  {
    id: 'toan6-c7-b1',
    grade: '6',
    chapterNumber: 7,
    chapterTitle: 'Số thập phân',
    lessonNumber: 1,
    title: 'Số thập phân và các phép tính với số thập phân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c7',
  },
  {
    id: 'toan6-c7-b2',
    grade: '6',
    chapterNumber: 7,
    chapterTitle: 'Số thập phân',
    lessonNumber: 2,
    title: 'Làm tròn và ước lượng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c7',
  },
  {
    id: 'toan6-c7-b3',
    grade: '6',
    chapterNumber: 7,
    chapterTitle: 'Số thập phân',
    lessonNumber: 3,
    title: 'Tỉ số và tỉ số phần trăm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c7',
  },
  {
    id: 'toan6-c8-b1',
    grade: '6',
    chapterNumber: 8,
    chapterTitle: 'Những hình hình học cơ bản',
    lessonNumber: 1,
    title: 'Điểm, đường thẳng và tia',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c8',
  },
  {
    id: 'toan6-c8-b2',
    grade: '6',
    chapterNumber: 8,
    chapterTitle: 'Những hình hình học cơ bản',
    lessonNumber: 2,
    title: 'Đoạn thẳng, độ dài đoạn thẳng và trung điểm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c8',
  },
  {
    id: 'toan6-c8-b3',
    grade: '6',
    chapterNumber: 8,
    chapterTitle: 'Những hình hình học cơ bản',
    lessonNumber: 3,
    title: 'Góc và số đo góc',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c8',
  },
  {
    id: 'toan6-c9-b1',
    grade: '6',
    chapterNumber: 9,
    chapterTitle: 'Dữ liệu và xác suất thực nghiệm',
    lessonNumber: 1,
    title: 'Thu thập, phân loại dữ liệu và bảng thống kê',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c9',
  },
  {
    id: 'toan6-c9-b2',
    grade: '6',
    chapterNumber: 9,
    chapterTitle: 'Dữ liệu và xác suất thực nghiệm',
    lessonNumber: 2,
    title: 'Biểu đồ tranh, biểu đồ cột và biểu đồ cột kép',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c9',
  },
  {
    id: 'toan6-c9-b3',
    grade: '6',
    chapterNumber: 9,
    chapterTitle: 'Dữ liệu và xác suất thực nghiệm',
    lessonNumber: 3,
    title: 'Kết quả có thể, sự kiện và xác suất thực nghiệm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan6c9',
  },
  {
    id: 'toan7-c1-b1',
    grade: '7',
    chapterNumber: 1,
    chapterTitle: 'Số hữu tỉ',
    lessonNumber: 1,
    title: 'Tập hợp các số hữu tỉ và thứ tự trên trục số',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c1',
  },
  {
    id: 'toan7-c1-b2',
    grade: '7',
    chapterNumber: 1,
    chapterTitle: 'Số hữu tỉ',
    lessonNumber: 2,
    title: 'Cộng, trừ, nhân, chia số hữu tỉ và quy tắc chuyển vế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c1',
  },
  {
    id: 'toan7-c1-b3',
    grade: '7',
    chapterNumber: 1,
    chapterTitle: 'Số hữu tỉ',
    lessonNumber: 3,
    title: 'Luỹ thừa với số mũ tự nhiên của một số hữu tỉ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c1',
  },
  {
    id: 'toan7-c2-b1',
    grade: '7',
    chapterNumber: 2,
    chapterTitle: 'Số thực',
    lessonNumber: 1,
    title: 'Số thập phân vô hạn tuần hoàn và làm tròn số',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c2',
  },
  {
    id: 'toan7-c2-b2',
    grade: '7',
    chapterNumber: 2,
    chapterTitle: 'Số thực',
    lessonNumber: 2,
    title: 'Số vô tỉ và căn bậc hai số học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c2',
  },
  {
    id: 'toan7-c2-b3',
    grade: '7',
    chapterNumber: 2,
    chapterTitle: 'Số thực',
    lessonNumber: 3,
    title: 'Tập hợp các số thực và giá trị tuyệt đối',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c2',
  },
  {
    id: 'toan7-c3-b1',
    grade: '7',
    chapterNumber: 3,
    chapterTitle: 'Góc và đường thẳng song song',
    lessonNumber: 1,
    title: 'Góc ở vị trí đặc biệt và tia phân giác của một góc',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c3',
  },
  {
    id: 'toan7-c3-b2',
    grade: '7',
    chapterNumber: 3,
    chapterTitle: 'Góc và đường thẳng song song',
    lessonNumber: 2,
    title: 'Hai đường thẳng song song và tiên đề Euclid',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c3',
  },
  {
    id: 'toan7-c3-b3',
    grade: '7',
    chapterNumber: 3,
    chapterTitle: 'Góc và đường thẳng song song',
    lessonNumber: 3,
    title: 'Định lí và chứng minh định lí',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c3',
  },
  {
    id: 'toan7-c4-b1',
    grade: '7',
    chapterNumber: 4,
    chapterTitle: 'Tam giác bằng nhau',
    lessonNumber: 1,
    title: 'Tổng các góc trong một tam giác',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c4',
  },
  {
    id: 'toan7-c4-b2',
    grade: '7',
    chapterNumber: 4,
    chapterTitle: 'Tam giác bằng nhau',
    lessonNumber: 2,
    title: 'Hai tam giác bằng nhau và ba trường hợp bằng nhau của tam giác',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c4',
  },
  {
    id: 'toan7-c4-b3',
    grade: '7',
    chapterNumber: 4,
    chapterTitle: 'Tam giác bằng nhau',
    lessonNumber: 3,
    title: 'Tam giác cân và đường trung trực của đoạn thẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c4',
  },
  {
    id: 'toan7-c5-b1',
    grade: '7',
    chapterNumber: 5,
    chapterTitle: 'Thu thập và biểu diễn dữ liệu',
    lessonNumber: 1,
    title: 'Thu thập, phân loại và đánh giá tính hợp lí của dữ liệu',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c5',
  },
  {
    id: 'toan7-c5-b2',
    grade: '7',
    chapterNumber: 5,
    chapterTitle: 'Thu thập và biểu diễn dữ liệu',
    lessonNumber: 2,
    title: 'Biểu đồ hình quạt tròn',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c5',
  },
  {
    id: 'toan7-c5-b3',
    grade: '7',
    chapterNumber: 5,
    chapterTitle: 'Thu thập và biểu diễn dữ liệu',
    lessonNumber: 3,
    title: 'Biểu đồ đoạn thẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c5',
  },
  {
    id: 'toan7-c6-b1',
    grade: '7',
    chapterNumber: 6,
    chapterTitle: 'Tỉ lệ thức và đại lượng tỉ lệ',
    lessonNumber: 1,
    title: 'Tỉ lệ thức và tính chất của dãy tỉ số bằng nhau',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c6',
  },
  {
    id: 'toan7-c6-b2',
    grade: '7',
    chapterNumber: 6,
    chapterTitle: 'Tỉ lệ thức và đại lượng tỉ lệ',
    lessonNumber: 2,
    title: 'Đại lượng tỉ lệ thuận',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c6',
  },
  {
    id: 'toan7-c6-b3',
    grade: '7',
    chapterNumber: 6,
    chapterTitle: 'Tỉ lệ thức và đại lượng tỉ lệ',
    lessonNumber: 3,
    title: 'Đại lượng tỉ lệ nghịch',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c6',
  },
  {
    id: 'toan7-c7-b1',
    grade: '7',
    chapterNumber: 7,
    chapterTitle: 'Biểu thức đại số và đa thức một biến',
    lessonNumber: 1,
    title: 'Biểu thức đại số và đa thức một biến',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c7',
  },
  {
    id: 'toan7-c7-b2',
    grade: '7',
    chapterNumber: 7,
    chapterTitle: 'Biểu thức đại số và đa thức một biến',
    lessonNumber: 2,
    title: 'Phép cộng và phép trừ đa thức một biến',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c7',
  },
  {
    id: 'toan7-c7-b3',
    grade: '7',
    chapterNumber: 7,
    chapterTitle: 'Biểu thức đại số và đa thức một biến',
    lessonNumber: 3,
    title: 'Phép nhân và phép chia đa thức một biến',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c7',
  },
  {
    id: 'toan7-c8-b1',
    grade: '7',
    chapterNumber: 8,
    chapterTitle: 'Làm quen với biến cố và xác suất của biến cố',
    lessonNumber: 1,
    title: 'Làm quen với biến cố ngẫu nhiên',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c8',
  },
  {
    id: 'toan7-c8-b2',
    grade: '7',
    chapterNumber: 8,
    chapterTitle: 'Làm quen với biến cố và xác suất của biến cố',
    lessonNumber: 2,
    title: 'Làm quen với xác suất của biến cố',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c8',
  },
  {
    id: 'toan7-c9-b1',
    grade: '7',
    chapterNumber: 9,
    chapterTitle: 'Quan hệ giữa các yếu tố trong một tam giác',
    lessonNumber: 1,
    title: 'Quan hệ giữa góc và cạnh đối diện, bất đẳng thức tam giác',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c9',
  },
  {
    id: 'toan7-c9-b2',
    grade: '7',
    chapterNumber: 9,
    chapterTitle: 'Quan hệ giữa các yếu tố trong một tam giác',
    lessonNumber: 2,
    title: 'Quan hệ giữa đường vuông góc và đường xiên',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c9',
  },
  {
    id: 'toan7-c9-b3',
    grade: '7',
    chapterNumber: 9,
    chapterTitle: 'Quan hệ giữa các yếu tố trong một tam giác',
    lessonNumber: 3,
    title: 'Sự đồng quy của các đường đặc biệt trong tam giác',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c9',
  },
  {
    id: 'toan7-c10-b1',
    grade: '7',
    chapterNumber: 10,
    chapterTitle: 'Một số hình khối trong thực tiễn',
    lessonNumber: 1,
    title: 'Hình hộp chữ nhật và hình lập phương',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c10',
  },
  {
    id: 'toan7-c10-b2',
    grade: '7',
    chapterNumber: 10,
    chapterTitle: 'Một số hình khối trong thực tiễn',
    lessonNumber: 2,
    title: 'Hình lăng trụ đứng tam giác và hình lăng trụ đứng tứ giác',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan7c10',
  },
  {
    id: 'toan10-c1-b1',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mệnh đề và tập hợp',
    lessonNumber: 1,
    title: 'Mệnh đề, mệnh đề kéo theo và mệnh đề phủ định',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c1',
  },
  {
    id: 'toan10-c1-b2',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mệnh đề và tập hợp',
    lessonNumber: 2,
    title: 'Tập hợp và các phép toán trên tập hợp',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c1',
  },
  {
    id: 'toan10-c2-b1',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bất phương trình và hệ bất phương trình bậc nhất hai ẩn',
    lessonNumber: 1,
    title: 'Miền nghiệm của bất phương trình bậc nhất hai ẩn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c2',
  },
  {
    id: 'toan10-c2-b2',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bất phương trình và hệ bất phương trình bậc nhất hai ẩn',
    lessonNumber: 2,
    title: 'Hệ bất phương trình bậc nhất hai ẩn và bài toán tối ưu',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c2',
  },
  {
    id: 'toan10-c3-b1',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Hệ thức lượng trong tam giác',
    lessonNumber: 1,
    title: 'Định lí côsin và định lí sin',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c3',
  },
  {
    id: 'toan10-c3-b2',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Hệ thức lượng trong tam giác',
    lessonNumber: 2,
    title: 'Giá trị lượng giác của góc từ 0° đến 180°',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c3',
  },
  {
    id: 'toan10-c3-b3',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Hệ thức lượng trong tam giác',
    lessonNumber: 3,
    title: 'Diện tích tam giác và giải tam giác trong thực tế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c3',
  },
  {
    id: 'toan10-c4-b1',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Vectơ',
    lessonNumber: 1,
    title: 'Vectơ và phép cộng vectơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c4',
  },
  {
    id: 'toan10-c4-b2',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Vectơ',
    lessonNumber: 2,
    title: 'Tích vô hướng của hai vectơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c4',
  },
  {
    id: 'toan10-c5-b1',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Các số đặc trưng của mẫu số liệu không ghép nhóm',
    lessonNumber: 1,
    title: 'Số gần đúng và sai số',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c5',
  },
  {
    id: 'toan10-c5-b2',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Các số đặc trưng của mẫu số liệu không ghép nhóm',
    lessonNumber: 2,
    title: 'Số trung bình, trung vị, tứ phân vị và mốt của mẫu số liệu không ghép nhóm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c5',
  },
  {
    id: 'toan10-c5-b3',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Các số đặc trưng của mẫu số liệu không ghép nhóm',
    lessonNumber: 3,
    title: 'Khoảng biến thiên, phương sai, độ lệch chuẩn và giá trị ngoại lệ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c5',
  },
  {
    id: 'toan10-c6-b1',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Hàm số, đồ thị và ứng dụng',
    lessonNumber: 1,
    title: 'Hàm số bậc hai và đồ thị parabol',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c6',
  },
  {
    id: 'toan10-c6-b2',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Hàm số, đồ thị và ứng dụng',
    lessonNumber: 2,
    title: 'Dấu của tam thức bậc hai và bất phương trình bậc hai',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c6',
  },
  {
    id: 'toan10-c7-b1',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Phương pháp toạ độ trong mặt phẳng',
    lessonNumber: 1,
    title: 'Phương trình đường thẳng và khoảng cách từ điểm đến đường thẳng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c7',
  },
  {
    id: 'toan10-c7-b2',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Phương pháp toạ độ trong mặt phẳng',
    lessonNumber: 2,
    title: 'Phương trình đường tròn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c7',
  },
  {
    id: 'toan10-c8-b1',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Đại số tổ hợp',
    lessonNumber: 1,
    title: 'Hoán vị, chỉnh hợp và tổ hợp',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c8',
  },
  {
    id: 'toan10-c8-b2',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Đại số tổ hợp',
    lessonNumber: 2,
    title: 'Nhị thức Newton',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c8',
  },
  {
    id: 'toan10-c9-b1',
    grade: '10',
    chapterNumber: 9,
    chapterTitle: 'Tính xác suất theo định nghĩa cổ điển',
    lessonNumber: 1,
    title: 'Không gian mẫu, biến cố và xác suất cổ điển',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c9',
  },
  {
    id: 'toan10-c9-b2',
    grade: '10',
    chapterNumber: 9,
    chapterTitle: 'Tính xác suất theo định nghĩa cổ điển',
    lessonNumber: 2,
    title: 'Biến cố đối và sơ đồ cây trong tính xác suất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c9',
  },
  {
    id: 'toan11-c1-b1',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Hàm số lượng giác và phương trình lượng giác',
    lessonNumber: 1,
    title: 'Giá trị lượng giác của góc lượng giác và đường tròn lượng giác',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c1',
  },
  {
    id: 'toan11-c1-b2',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Hàm số lượng giác và phương trình lượng giác',
    lessonNumber: 2,
    title: 'Phương trình lượng giác cơ bản',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c1',
  },
  {
    id: 'toan11-c2-b1',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Dãy số. Cấp số cộng và cấp số nhân',
    lessonNumber: 1,
    title: 'Cấp số cộng và cấp số nhân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c2',
  },
  {
    id: 'toan11-c2-b2',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Dãy số. Cấp số cộng và cấp số nhân',
    lessonNumber: 2,
    title: 'Dãy số: cách cho dãy, tính tăng giảm và bị chặn',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c2',
  },
  {
    id: 'toan11-c2-b3',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Dãy số. Cấp số cộng và cấp số nhân',
    lessonNumber: 3,
    title: 'Cấp số nhân trong bài toán lãi kép và tăng trưởng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c2',
  },
  {
    id: 'toan11-c3-b1',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo xu thế trung tâm của mẫu số liệu ghép nhóm',
    lessonNumber: 1,
    title: 'Mẫu số liệu ghép nhóm và giá trị đại diện của nhóm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c3',
  },
  {
    id: 'toan11-c3-b2',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo xu thế trung tâm của mẫu số liệu ghép nhóm',
    lessonNumber: 2,
    title: 'Số trung bình, trung vị, tứ phân vị và mốt của mẫu số liệu ghép nhóm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c3',
  },
  {
    id: 'toan11-c4-b1',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Quan hệ song song trong không gian',
    lessonNumber: 1,
    title: 'Xác định mặt phẳng và vị trí tương đối của hai đường thẳng trong không gian',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c4',
  },
  {
    id: 'toan11-c4-b2',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Quan hệ song song trong không gian',
    lessonNumber: 2,
    title: 'Quan hệ song song với mặt phẳng và định lí Thalès trong không gian',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c4',
  },
  {
    id: 'toan11-c4-b3',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Quan hệ song song trong không gian',
    lessonNumber: 3,
    title: 'Phép chiếu song song và hình biểu diễn của hình không gian',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c4',
  },
  {
    id: 'toan11-c5-b1',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Giới hạn. Hàm số liên tục',
    lessonNumber: 1,
    title: 'Giới hạn của dãy số và tổng cấp số nhân lùi vô hạn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c5',
  },
  {
    id: 'toan11-c5-b2',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Giới hạn. Hàm số liên tục',
    lessonNumber: 2,
    title: 'Giới hạn của hàm số và hàm số liên tục',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c5',
  },
  {
    id: 'toan11-c6-b1',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hàm số mũ và hàm số lôgarit',
    lessonNumber: 1,
    title: 'Lôgarit và các quy tắc tính',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c6',
  },
  {
    id: 'toan11-c6-b2',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hàm số mũ và hàm số lôgarit',
    lessonNumber: 2,
    title: 'Phương trình mũ và phương trình lôgarit',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c6',
  },
  {
    id: 'toan11-c7-b1',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 1,
    title: 'Đường thẳng vuông góc với mặt phẳng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan11-c7-b2',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 2,
    title: 'Hai đường thẳng vuông góc và góc giữa đường thẳng với mặt phẳng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan11-c7-b3',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 3,
    title: 'Hai mặt phẳng vuông góc và góc nhị diện',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan11-c7-b4',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 4,
    title: 'Khoảng cách trong không gian',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan11-c7-b5',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 5,
    title: 'Thể tích khối chóp, khối lăng trụ và khối chóp cụt đều',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan11-c8-b1',
    grade: '11',
    chapterNumber: 8,
    chapterTitle: 'Các quy tắc tính xác suất',
    lessonNumber: 1,
    title: 'Biến cố hợp, biến cố giao và biến cố độc lập',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c8',
  },
  {
    id: 'toan11-c8-b2',
    grade: '11',
    chapterNumber: 8,
    chapterTitle: 'Các quy tắc tính xác suất',
    lessonNumber: 2,
    title: 'Công thức cộng xác suất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c8',
  },
  {
    id: 'toan11-c8-b3',
    grade: '11',
    chapterNumber: 8,
    chapterTitle: 'Các quy tắc tính xác suất',
    lessonNumber: 3,
    title: 'Công thức nhân xác suất cho hai biến cố độc lập',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c8',
  },
  {
    id: 'toan10-c20-b1',
    grade: '10',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp trường',
    lessonNumber: 1,
    title: 'Bất đẳng thức AM–GM và kỹ thuật tìm giá trị nhỏ nhất',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c20',
  },
  {
    id: 'toan10-c20-b2',
    grade: '10',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp trường',
    lessonNumber: 2,
    title: 'Chia hết và đồng dư cơ bản trong số học',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c20',
  },
  {
    id: 'toan11-c9-b1',
    grade: '11',
    chapterNumber: 9,
    chapterTitle: 'Đạo hàm',
    lessonNumber: 1,
    title: 'Khái niệm đạo hàm và ý nghĩa hình học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c9',
  },
  {
    id: 'toan11-c9-b2',
    grade: '11',
    chapterNumber: 9,
    chapterTitle: 'Đạo hàm',
    lessonNumber: 2,
    title: 'Các quy tắc tính đạo hàm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c9',
  },
  {
    id: 'toan11-c9-b3',
    grade: '11',
    chapterNumber: 9,
    chapterTitle: 'Đạo hàm',
    lessonNumber: 3,
    title: 'Đạo hàm cấp hai và gia tốc tức thời',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c9',
  },
  {
    id: 'toan11-c20-b1',
    grade: '11',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp tỉnh',
    lessonNumber: 1,
    title: 'Bất đẳng thức Cauchy–Schwarz và kỹ thuật Cauchy–Schwarz dạng Engel',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c20',
  },
  {
    id: 'toan11-c20-b2',
    grade: '11',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp tỉnh',
    lessonNumber: 2,
    title: 'Phương tích của một điểm và trục đẳng phương',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c20',
  },
  {
    id: 'toan12-c1-b1',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    lessonNumber: 1,
    title: 'Tính đơn điệu và cực trị của hàm số',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c1',
  },
  {
    id: 'toan12-c1-b2',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    lessonNumber: 2,
    title: 'Đường tiệm cận của đồ thị hàm số',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c1',
  },
  {
    id: 'toan12-c2-b1',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 1,
    title: 'Vectơ trong không gian và các phép toán',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b2',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 2,
    title: 'Toạ độ của điểm và của vectơ trong không gian Oxyz',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b3',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 3,
    title: 'Biểu thức toạ độ của phép toán vectơ và tích vô hướng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b4',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 4,
    title: 'Ứng dụng toạ độ: khoảng cách giữa hai điểm và góc giữa hai đường thẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c3-b1',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 1,
    title: 'Khoảng biến thiên và khoảng tứ phân vị của mẫu số liệu ghép nhóm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c3-b2',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 2,
    title: 'Phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c3-b3',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 3,
    title: 'So sánh độ phân tán giữa hai mẫu số liệu và vận dụng thực tế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c4-b1',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Nguyên hàm và tích phân',
    lessonNumber: 1,
    title: 'Nguyên hàm — phép toán ngược của đạo hàm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c4',
  },
  {
    id: 'toan12-c4-b2',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Nguyên hàm và tích phân',
    lessonNumber: 2,
    title: 'Tích phân và ứng dụng tính diện tích, thể tích',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c4',
  },
  {
    id: 'toan12-c5-b1',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 1,
    title: 'Hệ toạ độ Oxyz và tích có hướng của hai vectơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c5-b2',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 2,
    title: 'Phương trình mặt phẳng và mặt cầu',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c5-b3',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 3,
    title: 'Phương trình đường thẳng trong không gian',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c5-b4',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 4,
    title: 'Công thức tính góc trong không gian',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c6-b1',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Xác suất có điều kiện',
    lessonNumber: 1,
    title: 'Xác suất có điều kiện và công thức Bayes',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c6',
  },
  {
    id: 'toan12-c6-b2',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Xác suất có điều kiện',
    lessonNumber: 2,
    title: 'Công thức xác suất toàn phần và bài toán xét nghiệm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c6',
  },
  {
    id: 'toan12-c20-b1',
    grade: '12',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi quốc gia',
    lessonNumber: 1,
    title: 'Phương trình hàm Cauchy và kỹ thuật thế giá trị đặc biệt',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c20',
  },
  {
    id: 'toan12-c20-b2',
    grade: '12',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi quốc gia',
    lessonNumber: 2,
    title: 'Bất biến và đơn biến trong bài toán tổ hợp',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c20',
  },
]

export const CHAPTER_LOADERS: Record<string, () => Promise<MathLesson[]>> = {
  toan6c1: () => import('./lessons/toan6c1.js').then((m) => m.TOAN6_C1_LESSONS),
  toan6c2: () => import('./lessons/toan6c2.js').then((m) => m.TOAN6_C2_LESSONS),
  toan6c3: () => import('./lessons/toan6c3.js').then((m) => m.TOAN6_C3_LESSONS),
  toan6c4: () => import('./lessons/toan6c4.js').then((m) => m.TOAN6_C4_LESSONS),
  toan6c5: () => import('./lessons/toan6c5.js').then((m) => m.TOAN6_C5_LESSONS),
  toan6c6: () => import('./lessons/toan6c6.js').then((m) => m.TOAN6_C6_LESSONS),
  toan6c7: () => import('./lessons/toan6c7.js').then((m) => m.TOAN6_C7_LESSONS),
  toan6c8: () => import('./lessons/toan6c8.js').then((m) => m.TOAN6_C8_LESSONS),
  toan6c9: () => import('./lessons/toan6c9.js').then((m) => m.TOAN6_C9_LESSONS),
  toan7c1: () => import('./lessons/toan7c1.js').then((m) => m.TOAN7_C1_LESSONS),
  toan7c2: () => import('./lessons/toan7c2.js').then((m) => m.TOAN7_C2_LESSONS),
  toan7c3: () => import('./lessons/toan7c3.js').then((m) => m.TOAN7_C3_LESSONS),
  toan7c4: () => import('./lessons/toan7c4.js').then((m) => m.TOAN7_C4_LESSONS),
  toan7c5: () => import('./lessons/toan7c5.js').then((m) => m.TOAN7_C5_LESSONS),
  toan7c6: () => import('./lessons/toan7c6.js').then((m) => m.TOAN7_C6_LESSONS),
  toan7c7: () => import('./lessons/toan7c7.js').then((m) => m.TOAN7_C7_LESSONS),
  toan7c8: () => import('./lessons/toan7c8.js').then((m) => m.TOAN7_C8_LESSONS),
  toan7c9: () => import('./lessons/toan7c9.js').then((m) => m.TOAN7_C9_LESSONS),
  toan7c10: () => import('./lessons/toan7c10.js').then((m) => m.TOAN7_C10_LESSONS),
  toan10c1: () => import('./lessons/toan10c1.js').then((m) => m.TOAN10_C1_LESSONS),
  toan10c2: () => import('./lessons/toan10c2.js').then((m) => m.TOAN10_C2_LESSONS),
  toan10c3: () => import('./lessons/toan10c3.js').then((m) => m.TOAN10_C3_LESSONS),
  toan10c4: () => import('./lessons/toan10c4.js').then((m) => m.TOAN10_C4_LESSONS),
  toan10c5: () => import('./lessons/toan10c5.js').then((m) => m.TOAN10_C5_LESSONS),
  toan10c6: () => import('./lessons/toan10c6.js').then((m) => m.TOAN10_C6_LESSONS),
  toan10c7: () => import('./lessons/toan10c7.js').then((m) => m.TOAN10_C7_LESSONS),
  toan10c8: () => import('./lessons/toan10c8.js').then((m) => m.TOAN10_C8_LESSONS),
  toan10c9: () => import('./lessons/toan10c9.js').then((m) => m.TOAN10_C9_LESSONS),
  toan11c1: () => import('./lessons/toan11c1.js').then((m) => m.TOAN11_C1_LESSONS),
  toan11c2: () => import('./lessons/toan11c2.js').then((m) => m.TOAN11_C2_LESSONS),
  toan11c3: () => import('./lessons/toan11c3.js').then((m) => m.TOAN11_C3_LESSONS),
  toan11c4: () => import('./lessons/toan11c4.js').then((m) => m.TOAN11_C4_LESSONS),
  toan11c5: () => import('./lessons/toan11c5.js').then((m) => m.TOAN11_C5_LESSONS),
  toan11c6: () => import('./lessons/toan11c6.js').then((m) => m.TOAN11_C6_LESSONS),
  toan11c7: () => import('./lessons/toan11c7.js').then((m) => m.TOAN11_C7_LESSONS),
  toan11c8: () => import('./lessons/toan11c8.js').then((m) => m.TOAN11_C8_LESSONS),
  toan10c20: () => import('./lessons/toan10c20.js').then((m) => m.TOAN10_C20_LESSONS),
  toan11c9: () => import('./lessons/toan11c9.js').then((m) => m.TOAN11_C9_LESSONS),
  toan11c20: () => import('./lessons/toan11c20.js').then((m) => m.TOAN11_C20_LESSONS),
  toan12c1: () => import('./lessons/toan12c1.js').then((m) => m.TOAN12_C1_LESSONS),
  toan12c2: () => import('./lessons/toan12c2.js').then((m) => m.TOAN12_C2_LESSONS),
  toan12c3: () => import('./lessons/toan12c3.js').then((m) => m.TOAN12_C3_LESSONS),
  toan12c4: () => import('./lessons/toan12c4.js').then((m) => m.TOAN12_C4_LESSONS),
  toan12c5: () => import('./lessons/toan12c5.js').then((m) => m.TOAN12_C5_LESSONS),
  toan12c6: () => import('./lessons/toan12c6.js').then((m) => m.TOAN12_C6_LESSONS),
  toan12c20: () => import('./lessons/toan12c20.js').then((m) => m.TOAN12_C20_LESSONS),
}
