// lessons/sinh10c4.ts — Sinh học 10, Chương 7 & 8 (Bài 20-26).
import type { BiologyLesson } from '../lessonTypes.js'

export const SINH10_C4_LESSONS: BiologyLesson[] = [
  {
    id: 'sinh10-c7-b20',
    animation: {
      title: 'Vi sinh vật nhân đôi theo cấp số nhân',
      description:
        'Đồ thị vẽ số tế bào của một quần thể vi khuẩn E. coli bắt đầu từ ĐÚNG MỘT tế bào, trong điều kiện tối ưu cứ 20 phút lại phân đôi một lần. Chấm sáng chạy dọc đường cong: sau 1 giờ có 3 lần phân đôi nên được 8 tế bào, sau 2 giờ là 64, sau 3 giờ là 512, sau 4 giờ đã hơn bốn nghìn. Công thức là N = N₀ × 2^(t/g) với g là thời gian thế hệ. Điều mà một câu văn không diễn tả nổi: đoạn đầu đường cong trông gần như phẳng, ai nhìn cũng tưởng chẳng có gì xảy ra, rồi nó dựng đứng lên rất đột ngột — đó chính là lý do một vết thức ăn nhiễm khuẩn để ngoài trời vài giờ có thể trở nên nguy hiểm, và vì sao vi sinh vật được dùng làm đối tượng sản xuất công nghiệp.',
      viewBoxWidth: 480,
      viewBoxHeight: 272,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 240,
          y: 20,
          text: 'Một tế bào sau mỗi 20 phút',
          size: 15,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'line',
          id: 'truc-x',
          x1: 62,
          y1: 236,
          x2: 452,
          y2: 236,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'truc-y',
          x1: 62,
          y1: 236,
          x2: 62,
          y2: 44,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-x',
          x: 452,
          y: 258,
          text: 'Thời gian (giờ)',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-y',
          x: 56,
          y: 32,
          text: 'Số tế bào',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'duong0',
          points: [
            [62, 236],
            [71.8, 235.9],
            [81.5, 235.9],
            [91.3, 235.9],
            [101, 235.9],
            [110.8, 235.9],
            [120.5, 235.8],
            [130.3, 235.8],
            [140, 235.8],
            [149.8, 235.7],
            [159.5, 235.6],
            [169.3, 235.5],
            [179, 235.4],
            [188.8, 235.3],
            [198.5, 235.1],
            [208.3, 234.9],
            [218, 234.7],
            [227.8, 234.4],
            [237.5, 234],
            [247.3, 233.6],
            [257, 233],
            [266.8, 232.3],
            [276.5, 231.5],
            [286.3, 230.4],
            [296, 229.1],
            [305.8, 227.5],
            [315.5, 225.6],
            [325.3, 223.1],
            [335, 220.2],
            [344.8, 216.5],
            [354.5, 212],
            [364.3, 206.5],
            [374, 199.6],
            [383.8, 191.2],
            [393.5, 180.9],
            [403.3, 168.1],
            [413, 152.4],
            [422.8, 133.1],
            [432.5, 109.3],
            [442.3, 80],
            [452, 44],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 0 },
            { atMs: 900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'diem-gc0',
          cx: 159.5,
          cy: 235.6,
          r: 4,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1900, opacity: 0 },
            { atMs: 2200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'diem-gc1',
          cx: 257,
          cy: 233,
          r: 4,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3500, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'diem-gc2',
          cx: 354.5,
          cy: 212,
          r: 4,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4900, opacity: 0 },
            { atMs: 5200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'diem-gc3',
          cx: 452,
          cy: 44,
          r: 4,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6300, opacity: 0 },
            { atMs: 6600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'cham-chay',
          cx: 62,
          cy: 236,
          r: 6,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 900, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1360, dx: 29.3, dy: -0.1, opacity: 1 },
            { atMs: 1820, dx: 48.8, dy: -0.1, opacity: 1 },
            { atMs: 2280, dx: 78, dy: -0.2, opacity: 1 },
            { atMs: 2740, dx: 107.3, dy: -0.5, opacity: 1 },
            { atMs: 3200, dx: 126.8, dy: -0.7, opacity: 1 },
            { atMs: 3660, dx: 156, dy: -1.3, opacity: 1 },
            { atMs: 4120, dx: 185.3, dy: -2.4, opacity: 1 },
            { atMs: 4580, dx: 204.8, dy: -3.7, opacity: 1 },
            { atMs: 5040, dx: 234, dy: -6.9, opacity: 1 },
            { atMs: 5500, dx: 263.3, dy: -12.9, opacity: 1 },
            { atMs: 5960, dx: 282.8, dy: -19.5, opacity: 1 },
            { atMs: 6420, dx: 312, dy: -36.4, opacity: 1 },
            { atMs: 6880, dx: 341.3, dy: -67.9, opacity: 1 },
            { atMs: 7340, dx: 360.8, dy: -102.9, opacity: 1 },
            { atMs: 7800, dx: 390, dy: -192, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc0',
          x: 159.5,
          y: 222,
          text: '1 giờ: 8',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1900, opacity: 0 },
            { atMs: 2200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc1',
          x: 257,
          y: 220,
          text: '2 giờ: 64',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3500, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc2',
          x: 346,
          y: 204,
          text: '3 giờ: 512',
          size: 12,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4900, opacity: 0 },
            { atMs: 5200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc3',
          x: 440,
          y: 50,
          text: '4 giờ: 4096',
          size: 12,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6300, opacity: 0 },
            { atMs: 6600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
      ],
      captions: [
        { atMs: 900, text: 'Bắt đầu từ đúng một tế bào vi khuẩn.' },
        {
          atMs: 2200,
          text: 'Thời gian thế hệ 20 phút: sau 1 giờ đã phân đôi 3 lần, được 8 tế bào.',
        },
        { atMs: 4200, text: 'Đoạn đầu trông gần như phẳng — dễ tưởng nhầm là chưa có gì xảy ra.' },
        {
          atMs: 6600,
          text: 'Sau 4 giờ đã hơn 4000 tế bào: N = N₀ × 2^(t/g), đường cong dựng đứng rất đột ngột.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 20,
    title: 'Khái quát về vi sinh vật',
    hook: 'Vi sinh vật siêu nhỏ bé, mắt thường không thể thấy được, nhưng chúng chiếm sinh khối khổng lồ và đóng vai trò quyết định trong việc tuần hoàn các nguyên tố hóa học trên Trái Đất.',
    theory:
      '## Khái niệm vi sinh vật\n' +
      '— Vi sinh vật (Microorganism) là những sinh vật có kích thước siêu nhỏ (tính bằng micrometer), cấu tạo đơn bào hoặc đa bào đơn giản (nhân sơ hoặc nhân thực), có khả năng hấp thụ và chuyển hóa chất dinh dưỡng nhanh, sinh trưởng và sinh sản rất nhanh, phân bố rộng rãi trong tự nhiên.\n' +
      '— Các nhóm vi sinh vật chính:\n' +
      '  + Vi sinh vật nhân sơ: Vi khuẩn (Bacteria), Cổ khuẩn (Archaea).\n' +
      '  + Vi sinh vật nhân thực: Vi tảo (Microalgae), Nấm men (Yeast), Nấm sợi, Động vật nguyên sinh (Protozoa).\n\n' +
      '## Các kiểu dinh dưỡng của vi sinh vật\n' +
      'Dựa vào nguồn năng lượng và nguồn carbon sử dụng, vi sinh vật được chia thành 4 kiểu dinh dưỡng chính:\n' +
      '1. Quang tự dưỡng (Photoautotrophy):\n' +
      '   — Nguồn năng lượng: Ánh sáng.\n' +
      '   — Nguồn carbon: CO₂.\n' +
      '   — Ví dụ: Vi khuẩn lam, tảo đơn bào, vi khuẩn lưu huỳnh màu tía và màu lục.\n' +
      '2. Hóa tự dưỡng (Chemoautotrophy):\n' +
      '   — Nguồn năng lượng: Chất vô cơ (NH₃, H₂S, NO₂⁻, Fe²⁺...).\n' +
      '   — Nguồn carbon: CO₂.\n' +
      '   — Ví dụ: Vi khuẩn nitrat hóa, vi khuẩn oxi hóa sắt, vi khuẩn oxi hóa lưu huỳnh.\n' +
      '3. Quang dị dưỡng (Photoheterotrophy):\n' +
      '   — Nguồn năng lượng: Ánh sáng.\n' +
      '   — Nguồn carbon: Chất hữu cơ.\n' +
      '   — Ví dụ: Vi khuẩn không lưu huỳnh màu lục và màu tía.\n' +
      '4. Hóa dị dưỡng (Chemoheterotrophy):\n' +
      '   — Nguồn năng lượng: Chất hữu cơ.\n' +
      '   — Nguồn carbon: Chất hữu cơ.\n' +
      '   — Ví dụ: Vi khuẩn phân hủy, nấm, động vật nguyên sinh, phần lớn vi khuẩn ký sinh.',
    workedExample: {
      problem:
        'Hãy so sánh sự khác nhau cơ bản về nguồn năng lượng và nguồn carbon giữa kiểu dinh dưỡng Quang tự dưỡng và Hóa dị dưỡng.',
      steps: [
        'Xác định tiêu chí so sánh: nguồn năng lượng và nguồn carbon.',
        'Đối với Quang tự dưỡng: Sử dụng năng lượng từ ánh sáng mặt trời; nguồn carbon để tổng hợp chất hữu cơ là chất vô cơ CO₂.',
        'Đối với Hóa dị dưỡng: Sử dụng năng lượng từ các liên kết hóa học trong chất hữu cơ; nguồn carbon cũng chính là các phân tử hữu cơ hấp thụ từ môi trường.',
      ],
      answer:
        'Quang tự dưỡng dùng ánh sáng và CO₂; Hóa dị dưỡng dùng chất hữu cơ làm cả nguồn năng lượng và nguồn carbon.',
    },
    checkQuestions: [
      {
        prompt: 'Nhóm vi sinh vật nào sau đây có kiểu dinh dưỡng hóa tự dưỡng?',
        choices: [
          { id: 'kt_1', label: 'Vi khuẩn nitrat hóa' },
          { id: 'kt_2', label: 'Nấm men bia' },
          { id: 'kt_3', label: 'Tảo lục đơn bào' },
          { id: 'kt_4', label: 'Vi khuẩn lam' },
        ],
        answer: { kind: 'choice', correctIds: ['kt_1'] },
        explain:
          'Vi khuẩn nitrat hóa oxi hóa NH₃ hoặc NO₂⁻ (chất vô cơ) để lấy năng lượng và dùng CO₂ làm nguồn carbon, đây là kiểu hóa tự dưỡng. Tảo lục và vi khuẩn lam là quang tự dưỡng; nấm men là hóa dị dưỡng.',
      },
      {
        prompt:
          'Vi sinh vật sử dụng nguồn năng lượng là ánh sáng và nguồn carbon là chất hữu cơ thuộc kiểu dinh dưỡng nào?',
        choices: [
          { id: 'kd_1', label: 'Quang dị dưỡng' },
          { id: 'kd_2', label: 'Quang tự dưỡng' },
          { id: 'kd_3', label: 'Hóa tự dưỡng' },
          { id: 'kd_4', label: 'Hóa dị dưỡng' },
        ],
        answer: { kind: 'choice', correctIds: ['kd_1'] },
        explain:
          'Sử dụng ánh sáng = Quang; sử dụng chất hữu cơ làm nguồn carbon = Dị dưỡng. Do đó đây là kiểu dinh dưỡng Quang dị dưỡng.',
      },
    ],
    srsCards: [
      {
        hoi: 'Nêu hai tiêu chí để phân chia các kiểu dinh dưỡng ở vi sinh vật?',
        dap: 'Nguồn năng lượng (Ánh sáng hoặc Chất hóa học) và Nguồn carbon (CO₂ hoặc Chất hữu cơ).',
      },
      {
        hoi: 'Kể tên các nhóm vi sinh vật có cấu tạo tế bào nhân sơ?',
        dap: 'Vi khuẩn (Bacteria) và Cổ khuẩn (Archaea).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c7-b21',
    animation: {
      title: 'Bốn pha sinh trưởng của quần thể vi khuẩn trong nuôi cấy không liên tục',
      description:
        'Đường cong chia làm bốn đoạn rõ rệt, chấm sáng chạy qua từng đoạn. Pha TIỀM PHÁT: số tế bào gần như không tăng vì vi khuẩn đang tổng hợp enzyme để làm quen môi trường mới — nó KHÔNG phải là pha chúng ngủ. Pha LUỸ THỪA: số tế bào tăng theo cấp số nhân, tốc độ phân chia đạt cực đại và ổn định, đây là pha người ta thu sinh khối. Pha CÂN BẰNG: đường nằm ngang, không phải vì vi khuẩn ngừng sinh sản mà vì số sinh ra đúng bằng số chết đi, do dinh dưỡng cạn và chất thải tích tụ. Pha SUY VONG: số chết vượt số sinh, đường đi xuống. Đặc điểm chỉ hình động nói rõ: một đường nằm ngang ở giữa vẫn là một quần thể đang sinh sản rất mạnh.',
      viewBoxWidth: 480,
      viewBoxHeight: 272,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 240,
          y: 20,
          text: 'Đường cong sinh trưởng 4 pha',
          size: 15,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'line',
          id: 'truc-x',
          x1: 62,
          y1: 236,
          x2: 452,
          y2: 236,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'truc-y',
          x1: 62,
          y1: 236,
          x2: 62,
          y2: 44,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-x',
          x: 452,
          y: 258,
          text: 'Thời gian',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-y',
          x: 56,
          y: 32,
          text: 'Log số tế bào',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'line',
          id: 'gd0',
          x1: 62,
          y1: 197.6,
          x2: 452,
          y2: 197.6,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 4',
        },
        {
          kind: 'polyline',
          id: 'duong0',
          points: [
            [62, 197.6],
            [81.5, 197.6],
            [101, 195.7],
            [120.5, 191.8],
            [140, 178.4],
            [159.5, 155.4],
            [179, 130.4],
            [198.5, 105.4],
            [218, 86.2],
            [237.5, 70.9],
            [257, 63.2],
            [288.2, 59.4],
            [319.4, 59.4],
            [342.8, 61.3],
            [366.2, 67],
            [393.5, 86.2],
            [420.8, 117],
            [452, 155.4],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 0 },
            { atMs: 900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'cham-chay',
          cx: 62,
          cy: 197.6,
          r: 6,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 900, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1360, dx: 19.5, dy: 0, opacity: 1 },
            { atMs: 1820, dx: 39, dy: -1.9, opacity: 1 },
            { atMs: 2280, dx: 58.5, dy: -5.8, opacity: 1 },
            { atMs: 2740, dx: 97.5, dy: -42.2, opacity: 1 },
            { atMs: 3200, dx: 117, dy: -67.2, opacity: 1 },
            { atMs: 3660, dx: 136.5, dy: -92.2, opacity: 1 },
            { atMs: 4120, dx: 156, dy: -111.4, opacity: 1 },
            { atMs: 4580, dx: 175.5, dy: -126.7, opacity: 1 },
            { atMs: 5040, dx: 195, dy: -134.4, opacity: 1 },
            { atMs: 5500, dx: 226.2, dy: -138.2, opacity: 1 },
            { atMs: 5960, dx: 257.4, dy: -138.2, opacity: 1 },
            { atMs: 6420, dx: 304.2, dy: -130.6, opacity: 1 },
            { atMs: 6880, dx: 331.5, dy: -111.4, opacity: 1 },
            { atMs: 7340, dx: 358.8, dy: -80.6, opacity: 1 },
            { atMs: 7800, dx: 390, dy: -42.2, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc0',
          x: 97.1,
          y: 224.5,
          text: 'Tiềm phát',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1300, opacity: 0 },
            { atMs: 1600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc1',
          x: 190.7,
          y: 224.5,
          text: 'Luỹ thừa',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2700, opacity: 0 },
            { atMs: 3000, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc2',
          x: 307.7,
          y: 224.5,
          text: 'Cân bằng',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc3',
          x: 413,
          y: 224.5,
          text: 'Suy vong',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5900, opacity: 0 },
            { atMs: 6200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc4',
          x: 307.7,
          y: 44,
          text: 'sinh ra = chết đi',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 1600,
          text: 'Pha tiềm phát: chưa tăng số lượng nhưng đang tổng hợp enzyme thích nghi — không phải đang ngủ.',
        },
        {
          atMs: 3000,
          text: 'Pha luỹ thừa: tốc độ phân chia cực đại và ổn định, đây là lúc thu sinh khối.',
        },
        {
          atMs: 4600,
          text: 'Pha cân bằng: đường nằm ngang vì số sinh ra bằng số chết đi, do cạn dinh dưỡng và tích chất thải.',
        },
        { atMs: 6200, text: 'Pha suy vong: số chết vượt số sinh, quần thể giảm.' },
      ],
    },
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 21,
    title: 'Trao đổi chất, sinh trưởng và sinh sản ở vi sinh vật',
    hook: 'Tại sao thức ăn để ngoài không khí rất nhanh bị ôi thiu? Đó là do tốc độ sinh trưởng và phân chia tế bào cực nhanh của vi sinh vật dưới điều kiện thuận lợi.',
    theory:
      '## Quá trình tổng hợp và phân giải ở vi sinh vật\n' +
      '— Tổng hợp: Vi sinh vật tổng hợp protein, nucleic acid, carbohydrate, lipid để kiến tạo tế bào. Nhiều nhóm có khả năng tự tổng hợp các amino acid thiết yếu.\n' +
      '— Phân giải: Vi sinh vật tiết enzyme ngoại bào (protease, amylase, lipase, cellulase...) để phân giải các chất hữu cơ phức tạp trong môi trường thành chất đơn giản, sau đó hấp thụ qua màng sinh chất.\n\n' +
      '## Sinh trưởng của quần thể vi sinh vật\n' +
      'Sinh trưởng của vi sinh vật được định nghĩa là sự gia tăng số lượng tế bào của quần thể.\n' +
      '1. Nuôi cấy không liên tục (Batch culture): Không bổ sung chất dinh dưỡng mới và không lấy đi chất thải sinh ra. Quần thể trải qua 4 pha sinh trưởng:\n' +
      '   — Pha tiềm phát (Lag phase): Tế bào thích nghi với môi trường mới, không phân chia số lượng, enzyme được tổng hợp mạnh mẽ.\n' +
      '   — Pha lũy thừa (Log phase): Tế bào phân chia với tốc độ tối đa, số lượng tế bào tăng theo cấp số nhân (hằng số sinh trưởng đạt cực đại).\n' +
      '   — Pha cân bằng (Stationary phase): Tốc độ sinh sản bằng tốc độ chết đi. Số lượng tế bào đạt cực đại và không đổi do dinh dưỡng giảm dần, chất độc tích lũy.\n' +
      '   — Pha suy vong (Decline phase): Số lượng tế bào chết vượt trội tế bào sinh ra do dinh dưỡng cạn kiệt, chất độc quá nhiều.\n' +
      '2. Nuôi cấy liên tục (Continuous culture): Bổ sung chất dinh dưỡng mới liên tục và lấy ra lượng dịch nuôi cấy tương đương. Quần thể luôn duy trì ở pha lũy thừa, ứng dụng thu sinh khối và chất kháng sinh.\n\n' +
      '## Hình thức sinh sản ở vi sinh vật\n' +
      '— Vi sinh vật nhân sơ: Phân đôi (phổ biến nhất), nảy chồi và hình thành bào tử sinh sản (như xạ khuẩn). Lưu ý: Nội bào tử (Endospore) ở vi khuẩn chỉ là dạng nghỉ chống chịu điều kiện bất lợi, không phải bào tử sinh sản.\n' +
      '— Vi sinh vật nhân thực: Sinh sản vô tính (phân đôi, nảy chồi, tạo bào tử vô tính) và sinh sản hữu tính (bằng bào tử hữu tính hoặc tiếp hợp).',
    workedExample: {
      problem:
        'Một quần thể vi khuẩn E. coli ban đầu có 200 tế bào được nuôi cấy trong điều kiện tối ưu. Biết thời gian thế hệ g = 20 phút. Hãy tính số lượng tế bào trong quần thể sau 2 giờ.',
      steps: [
        'Tính số lần phân chia (n): Thời gian nuôi cấy t = 2 giờ = 120 phút. Số lần phân chia n = t / g = 120 / 20 = 6 lần.',
        'Áp dụng công thức tính số lượng tế bào: N = N₀ × 2ⁿ, trong đó N₀ là số tế bào ban đầu, n là số lần phân chia.',
        'Tính toán: N = 200 × 2⁶ = 200 × 64 = 12800 tế bào.',
      ],
      answer: 'Số lượng tế bào vi khuẩn sau 2 giờ là 12.800 tế bào.',
    },
    checkQuestions: [
      {
        prompt:
          'Trong nuôi cấy không liên tục, pha nào có tốc độ sinh trưởng của quần thể vi sinh vật đạt cực đại?',
        choices: [
          { id: 'ps_1', label: 'Pha lũy thừa (Log phase)' },
          { id: 'ps_2', label: 'Pha tiềm phát (Lag phase)' },
          { id: 'ps_3', label: 'Pha cân bằng (Stationary phase)' },
          { id: 'ps_4', label: 'Pha suy vong (Decline phase)' },
        ],
        answer: { kind: 'choice', correctIds: ['ps_1'] },
        explain:
          'Trong pha lũy thừa, các điều kiện dinh dưỡng còn dồi dào, tế bào sinh trưởng và phân chia với tốc độ tối đa, số lượng tăng vọt theo lũy thừa.',
      },
      {
        prompt:
          'Cấu trúc nào sau đây ở vi khuẩn KHÔNG phải là hình thức sinh sản mà chỉ là dạng bảo vệ tế bào vượt qua điều kiện bất lợi?',
        choices: [
          { id: 'bt_1', label: 'Nội bào tử (Endospore)' },
          { id: 'bt_2', label: 'Bào tử đốt' },
          { id: 'bt_3', label: 'Nảy chồi' },
          { id: 'bt_4', label: 'Phân đôi' },
        ],
        answer: { kind: 'choice', correctIds: ['bt_1'] },
        explain:
          'Nội bào tử (endospore) của vi khuẩn hình thành khi môi trường khắc nghiệt. Khi điều kiện thuận lợi, mỗi nội bào tử chỉ nảy mầm thành một tế bào vi khuẩn duy nhất, không làm tăng số lượng cá thể nên không phải là sinh sản.',
      },
    ],
    srsCards: [
      {
        hoi: 'Thời gian thế hệ (g) của vi sinh vật là gì?',
        dap: 'Là khoảng thời gian cần thiết để số lượng tế bào trong quần thể vi sinh vật tăng lên gấp đôi (hoặc thời gian của một chu kỳ phân chia).',
      },
      {
        hoi: 'Tại sao nuôi cấy liên tục lại giữ được quần thể vi sinh vật ở pha lũy thừa?',
        dap: 'Vì liên tục bổ sung chất dinh dưỡng mới và đồng thời loại bỏ các chất độc hại cùng sinh khối dư thừa.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c7-b22',
    animation: {
      title: 'Lên men lactic: đường giảm, acid tăng, pH hạ',
      description:
        'Ba đường biến thiên cùng vẽ trên một trục thời gian của mẻ sữa chua hoặc vại dưa muối. Đường biểu diễn lượng ĐƯỜNG trong nguyên liệu đi xuống vì vi khuẩn lactic phân giải lactose hoặc glucose trong điều kiện kị khí. Đường biểu diễn ACID LACTIC đi lên vì đó là sản phẩm của quá trình lên men. Đường biểu diễn pH đi xuống theo, từ khoảng 6,5 xuống dưới 4,6 — tới ngưỡng đó protein sữa đông lại thành sữa chua, còn trong vại dưa thì môi trường chua ức chế vi khuẩn gây thối. Điều mà một câu văn khó nói: ba đại lượng này không tách rời mà là ba cách nhìn cùng một phản ứng, và chính sản phẩm do vi khuẩn tạo ra lại là thứ về sau kìm hãm chính chúng.',
      viewBoxWidth: 480,
      viewBoxHeight: 272,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 240,
          y: 20,
          text: 'Muối dưa và làm sữa chua theo thời gian',
          size: 15,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'line',
          id: 'truc-x',
          x1: 62,
          y1: 236,
          x2: 452,
          y2: 236,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'truc-y',
          x1: 62,
          y1: 236,
          x2: 62,
          y2: 44,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-x',
          x: 452,
          y: 258,
          text: 'Thời gian ủ (giờ)',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-y',
          x: 56,
          y: 40,
          text: 'Mức tương đối',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'duong0',
          points: [
            [62, 65.6],
            [81.5, 66.9],
            [101, 68.9],
            [120.5, 71.9],
            [140, 76.4],
            [159.5, 82.8],
            [179, 91.7],
            [198.5, 103.2],
            [218, 117],
            [237.5, 132.3],
            [257, 147.6],
            [276.5, 161.5],
            [296, 173],
            [315.5, 181.8],
            [335, 188.3],
            [354.5, 192.7],
            [374, 195.8],
            [393.5, 197.8],
            [413, 199.1],
            [432.5, 199.9],
            [452, 200.5],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 0 },
            { atMs: 900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'dl0',
          x: 68,
          y: 58,
          text: 'Đường',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 900, opacity: 0 },
            { atMs: 1300, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'cham-chay',
          cx: 62,
          cy: 65.6,
          r: 6,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 900, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1360, dx: 19.5, dy: 1.3, opacity: 1 },
            { atMs: 1820, dx: 58.5, dy: 6.3, opacity: 1 },
            { atMs: 2280, dx: 78, dy: 10.8, opacity: 1 },
            { atMs: 2740, dx: 97.5, dy: 17.2, opacity: 1 },
            { atMs: 3200, dx: 136.5, dy: 37.6, opacity: 1 },
            { atMs: 3660, dx: 156, dy: 51.4, opacity: 1 },
            { atMs: 4120, dx: 175.5, dy: 66.7, opacity: 1 },
            { atMs: 4580, dx: 214.5, dy: 95.9, opacity: 1 },
            { atMs: 5040, dx: 234, dy: 107.4, opacity: 1 },
            { atMs: 5500, dx: 253.5, dy: 116.2, opacity: 1 },
            { atMs: 5960, dx: 292.5, dy: 127.1, opacity: 1 },
            { atMs: 6420, dx: 312, dy: 130.2, opacity: 1 },
            { atMs: 6880, dx: 331.5, dy: 132.2, opacity: 1 },
            { atMs: 7340, dx: 370.5, dy: 134.3, opacity: 1 },
            { atMs: 7800, dx: 390, dy: 134.9, opacity: 1 },
          ],
        },
        {
          kind: 'polyline',
          id: 'duong1',
          points: [
            [62, 218.1],
            [81.5, 216.7],
            [101, 214.5],
            [120.5, 211.2],
            [140, 206.4],
            [159.5, 199.4],
            [179, 189.8],
            [198.5, 177.4],
            [218, 162.3],
            [237.5, 145.8],
            [257, 129.2],
            [276.5, 114.2],
            [296, 101.7],
            [315.5, 92.1],
            [335, 85.2],
            [354.5, 80.3],
            [374, 77],
            [393.5, 74.9],
            [413, 73.4],
            [432.5, 72.5],
            [452, 71.9],
          ],
          stroke: 'accent',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2400, opacity: 0 },
            { atMs: 2900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'dl1',
          x: 452,
          y: 63.900000000000006,
          text: 'Acid lactic',
          size: 12,
          anchor: 'end',
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2900, opacity: 0 },
            { atMs: 3300, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'polyline',
          id: 'duong2',
          points: [
            [62, 98.8],
            [81.5, 99.4],
            [101, 100.3],
            [120.5, 101.7],
            [140, 103.8],
            [159.5, 106.9],
            [179, 111.4],
            [198.5, 117.5],
            [218, 125.5],
            [237.5, 135.1],
            [257, 145.8],
            [276.5, 156.4],
            [296, 166],
            [315.5, 174],
            [335, 180.1],
            [354.5, 184.6],
            [374, 187.7],
            [393.5, 189.8],
            [413, 191.2],
            [432.5, 192.1],
            [452, 192.7],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4200, opacity: 0 },
            { atMs: 4700, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'dl2',
          x: 68,
          y: 92,
          text: 'pH',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4700, opacity: 0 },
            { atMs: 5100, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc0',
          x: 318,
          y: 140,
          text: 'pH < 4,6: sữa đông lại',
          size: 12,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5500, opacity: 0 },
            { atMs: 5800, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 900,
          text: 'Lượng đường trong nguyên liệu giảm dần: vi khuẩn lactic phân giải nó trong điều kiện kị khí.',
        },
        { atMs: 3000, text: 'Acid lactic tăng lên — đó là sản phẩm chính của quá trình lên men.' },
        { atMs: 4800, text: 'pH hạ từ khoảng 6,5 xuống dưới 4,6.' },
        {
          atMs: 5800,
          text: 'Tới ngưỡng đó protein sữa đông thành sữa chua, môi trường chua ức chế vi khuẩn gây thối.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 22,
    title: 'Vai trò và ứng dụng của vi sinh vật',
    hook: 'Sữa chua thơm ngon, nước mắm đậm đà, hay các loại thuốc kháng sinh cứu sống hàng triệu người đều là sản phẩm từ hoạt động chuyển hóa của các vi sinh vật nhỏ bé.',
    theory:
      '## Vai trò của vi sinh vật trong tự nhiên\n' +
      '— Phân giải các hợp chất hữu cơ (xác động thực vật) thành chất vô cơ cung cấp cho thực vật, khép kín chu trình tuần hoàn vật chất.\n' +
      '— Cố định nitrogen khí quyển (đạm) nhờ các vi khuẩn tự do (Azotobacter) hoặc cộng sinh (Rhizobium trong rễ cây họ Đậu), giúp tăng độ phì nhiêu của đất.\n\n' +
      '## Ứng dụng của vi sinh vật trong đời sống\n' +
      '1. Công nghệ thực phẩm:\n' +
      '   — Lên men lactic: Sản xuất sữa chua, muối dưa cà, nem chua nhờ vi khuẩn lactic (Lactobacillus).\n' +
      '   — Lên men ethanol: Sản xuất rượu, bia, bánh mì nhờ nấm men (Saccharomyces cerevisiae).\n' +
      '   — Sản xuất nước mắm, nước tương nhờ phân giải protein của nấm mốc hoặc vi khuẩn hữu ích.\n' +
      '2. Y học:\n' +
      '   — Sản xuất kháng sinh tự nhiên hoặc bán tổng hợp nhờ nấm mốc (Penicillium) hoặc xạ khuẩn (Streptomyces).\n' +
      '   — Chuyển gene sản xuất hormone (như insulin trị tiểu đường) hoặc interferon trị virus bằng vi khuẩn E. coli.\n' +
      '3. Nông nghiệp:\n' +
      '   — Sản xuất phân bón vi sinh (chứa vi khuẩn cố định đạm, phân giải lân).\n' +
      '   — Sản xuất thuốc trừ sâu sinh học (ví dụ vi khuẩn Bacillus thuringiensis - Bt sản xuất tinh thể độc diệt sâu hại).\n' +
      '4. Bảo vệ môi trường:\n' +
      '   — Xử lý nước thải bằng bể hiếu khí chứa bùn hoạt tính (chứa vi sinh vật phân hủy chất hữu cơ).\n' +
      '   — Xử lý tràn dầu bằng các chủng vi khuẩn phân hủy hydrocarbon.\n\n' +
      '## Tác hại của vi sinh vật\n' +
      '— Gây bệnh truyền nhiễm cho con người (lao, tả, thương hàn), động vật và thực vật.\n' +
      '— Làm hư hỏng, ôi thiu thực phẩm, gây độc tố nấm mốc (aflatoxin ở lạc mốc).',
    workedExample: {
      problem:
        'Giải thích tại sao khi làm sữa chua, sữa đặc có đường pha loãng sau một thời gian ủ ấm lại chuyển sang trạng thái đông tụ và có vị chua.',
      steps: [
        'Vi khuẩn lactic có sẵn trong hộp sữa chua mồi sử dụng đường lactose trong sữa làm nguồn carbon và năng lượng.',
        'Quá trình lên men lactic xảy ra: đường lactose chuyển thành acid lactic, làm giảm pH của môi trường sữa xuống khoảng 4,5.',
        'pH giảm khiến protein casein trong sữa bị đông tụ (kết tủa sinh học), tạo trạng thái mịn dẻo, đồng thời acid lactic tạo vị chua đặc trưng cho sữa chua.',
      ],
      answer:
        'Vi khuẩn lactic lên men đường thành acid lactic làm giảm pH, gây đông tụ protein casein trong sữa và tạo vị chua.',
    },
    checkQuestions: [
      {
        prompt:
          'Vi sinh vật nào sau đây được ứng dụng phổ biến để sản xuất penicillin phục vụ ngành y tế?',
        choices: [
          { id: 'ud_1', label: 'Nấm mốc Penicillium' },
          { id: 'ud_2', label: 'Vi khuẩn Escherichia coli' },
          { id: 'ud_3', label: 'Nấm men Saccharomyces' },
          { id: 'ud_4', label: 'Xạ khuẩn Streptomyces' },
        ],
        answer: { kind: 'choice', correctIds: ['ud_1'] },
        explain:
          'Kháng sinh penicillin được phát hiện và chiết xuất đầu tiên từ nấm mốc thuộc chi Penicillium (cụ thể là Penicillium notatum).',
      },
      {
        prompt:
          'Quá trình muối dưa, muối cà đạt yêu cầu là nhờ hoạt động chuyển hóa của nhóm vi sinh vật nào?',
        choices: [
          { id: 'lh_1', label: 'Vi khuẩn lactic' },
          { id: 'lh_2', label: 'Nấm men sinh cồn' },
          { id: 'lh_3', label: 'Nấm mốc phân giải cellulose' },
          { id: 'lh_4', label: 'Vi khuẩn cố định đạm' },
        ],
        answer: { kind: 'choice', correctIds: ['lh_1'] },
        explain:
          'Muối dưa cà dựa trên quá trình lên men lactic của vi khuẩn lactic có sẵn trên bề mặt lá rau quả, chuyển hóa đường thành acid lactic giúp bảo quản rau quả chống thiu hỏng.',
      },
    ],
    srsCards: [
      {
        hoi: 'Thuốc trừ sâu sinh học Bt được sản xuất dựa trên tác nhân vi sinh vật nào?',
        dap: 'Vi khuẩn Bacillus thuringiensis (Bt), có khả năng sinh độc tố dạng tinh thể tiêu diệt côn trùng hại cây.',
      },
      {
        hoi: 'Tại sao vi khuẩn Rhizobium lại có lợi cho cây họ Đậu?',
        dap: 'Vì chúng cộng sinh ở nốt sần rễ cây, chuyển hóa nitơ tự do (N₂) thành dạng ion amoni (NH₄⁺) mà cây có thể hấp thụ được.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c7-b23',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 23,
    title: 'Thực hành: Một số phương pháp nghiên cứu vi sinh vật',
    hook: 'Làm thế nào để phân lập được một dòng vi khuẩn tinh khiết từ mẫu đất vườn? Điều này đòi hỏi những kỹ thuật vô trùng cực kỳ nghiêm ngặt và sự khéo léo trong thao tác.',
    theory:
      '## Nguyên tắc vô trùng trong nghiên cứu vi sinh vật\n' +
      '— Khử trùng dụng cụ (đĩa Petri, ống nghiệm, que cấy) bằng cách hấp áp suất (autoclave) ở 121°C trong 15-20 phút hoặc sấy khô ở 160-180°C.\n' +
      '— Mọi thao tác cấy truyền vi sinh vật phải được thực hiện trong tủ cấy vô trùng hoặc bên cạnh ngọn lửa đèn cồn để tránh nhiễm chéo từ bào tử nấm/khuẩn ngoài không khí.\n\n' +
      '## Một số phương pháp nghiên cứu cơ bản\n' +
      '1. Phương pháp quan sát (Làm tiêu bản hiển vi):\n' +
      '   — Làm vết bôi vi khuẩn trên lam kính, cố định bằng nhiệt nhẹ.\n' +
      '   — Nhuộm màu (nhuộm đơn bằng xanh methylene hoặc nhuộm kép Gram). Nhuộm Gram giúp phân biệt vi khuẩn Gram dương (thành peptidoglycan dày, giữ màu tím kết tinh) và Gram âm (thành mỏng hơn có màng ngoài, bắt màu đỏ safranin sau khi tẩy cồn).\n' +
      '2. Phương pháp phân lập vi sinh vật (Cô lập tế bào đơn lẻ):\n' +
      '   — Phương pháp cấy ria (Streak plate): Dùng que cấy kim loại vạch các đường ziczac phân tán vi khuẩn trên đĩa thạch dinh dưỡng. Sau khi ủ, các tế bào đơn lẻ phát triển thành các khuẩn lạc (colony) tinh khiết biệt lập.\n' +
      '3. Phương pháp nuôi cấy và định lượng:\n' +
      '   — Nuôi cấy trên môi trường thạch đặc hoặc dịch thể để đo mật độ đục hoặc đếm khuẩn lạc để xác định số lượng tế bào sinh sống.',
    workedExample: {
      problem:
        'Mô tả tóm tắt 4 bước chính trong quy trình nhuộm Gram để phân biệt vi khuẩn Gram dương và Gram âm.',
      steps: [
        'Bước 1: Nhỏ thuốc thử nhuộm chính là tím kết tinh (Crystal violet) lên vết bôi vi khuẩn đã cố định bằng nhiệt trong 1 phút, rửa nước. Cả hai nhóm đều bắt màu tím.',
        'Bước 2: Nhỏ dung dịch Iốt (Lugol) làm chất gắn màu trong 1 phút, rửa nước. Tạo phức chất tím kết tinh-iốt lớn trong tế bào.',
        'Bước 3: Tẩy màu bằng cồn 95% (Ethanol) trong 10-30 giây rồi rửa nhanh bằng nước. Gram âm bị mất màu do lớp màng ngoài bị hòa tan và thành mỏng; Gram dương giữ màu tím do thành peptidoglycan dày co lại giữ phức màu.',
        'Bước 4: Nhuộm bổ sung bằng dung dịch Safranin (màu hồng đỏ) trong 1 phút, rửa nước, thấm khô. Gram âm bắt màu hồng đỏ; Gram dương giữ nguyên màu tím.',
      ],
      answer:
        'Quy trình gồm: Nhuộm tím kết tinh -> Gắn màu bằng Iốt -> Tẩy màu bằng cồn -> Nhuộm bổ sung bằng safranin.',
    },
    checkQuestions: [
      {
        prompt:
          'Trong kỹ thuật nhuộm Gram, vi khuẩn Gram âm sẽ có màu sắc gì dưới kính hiển vi khi kết thúc quá trình?',
        choices: [
          { id: 'gr_1', label: 'Màu hồng đỏ' },
          { id: 'gr_2', label: 'Màu tím kết tinh' },
          { id: 'gr_3', label: 'Màu xanh lục' },
          { id: 'gr_4', label: 'Không màu (trong suốt)' },
        ],
        answer: { kind: 'choice', correctIds: ['gr_1'] },
        explain:
          'Vi khuẩn Gram âm bị tẩy màu bởi cồn, sau đó bắt màu của thuốc nhuộm bổ sung safranin nên có màu hồng đỏ dưới kính hiển vi.',
      },
      {
        prompt:
          'Để phân lập các khuẩn lạc vi khuẩn riêng rẽ từ một hỗn hợp ban đầu trên đĩa thạch dinh dưỡng, phương pháp nào sau đây được sử dụng phổ biến nhất?',
        choices: [
          { id: 'pl_1', label: 'Phương pháp cấy ria (Streak plate)' },
          { id: 'pl_2', label: 'Phương pháp nhuộm đơn' },
          { id: 'pl_3', label: 'Nuôi cấy trong môi trường dịch thể liên tục' },
          { id: 'pl_4', label: 'Hấp khử trùng ở 121°C' },
        ],
        answer: { kind: 'choice', correctIds: ['pl_1'] },
        explain:
          'Phương pháp cấy ria trên đĩa thạch giúp pha loãng cơ học mật độ vi khuẩn theo từng phân vùng đường cấy, tạo điều kiện cho các tế bào đơn lẻ tách rời và phát triển thành các khuẩn lạc thuần khiết độc lập.',
      },
    ],
    srsCards: [
      {
        hoi: 'Tại sao vi khuẩn Gram dương giữ được màu tím sau khi tẩy cồn?',
        dap: 'Vì thành tế bào peptidoglycan dày ngăn cản sự rửa trôi phức chất tím kết tinh-iốt ra khỏi tế bào khi tiếp xúc với cồn.',
      },
      {
        hoi: 'Tại sao phải đốt nóng đỏ que cấy trên ngọn lửa đèn cồn trước và sau khi cấy?',
        dap: 'Trước khi cấy: Tiêu diệt mọi vi sinh vật bám trên que cấy tránh nhiễm mẫu; Sau khi cấy: Tiêu diệt vi sinh vật còn bám trên que cấy tránh phát tán ra môi trường.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c8-b24',
    animation: {
      title: 'Năm giai đoạn nhân lên của virus trong tế bào chủ',
      description:
        'Một phage (đầu lục giác chứa acid nucleic màu cam, đuôi và hai sợi chân) rơi xuống bám vào hai thụ thể xanh trên màng vi khuẩn: HẤP PHỤ, chỉ bám được khi khớp đặc hiệu với thụ thể. XÂM NHẬP: sợi acid nucleic từ đầu phage đi xuống vào trong tế bào, vỏ capsid rỗng ở lại bên ngoài và mờ đi. SINH TỔNG HỢP: trong tế bào xuất hiện thêm các sợi acid nucleic mới, các đầu capsid và đuôi rời, tất cả do bộ máy của tế bào chủ làm ra theo lệnh của gene virus. LẮP RÁP: mỗi sợi acid nucleic trượt vào một đầu capsid, đuôi gắn vào bên dưới, thành ba hạt virus hoàn chỉnh. PHÓNG THÍCH: màng tế bào vỡ thành từng mảnh, ba virus mới thoát ra ba phía (chu trình sinh tan). Hình vẽ phage; nhiều virus động vật thì vào cả hạt rồi cởi vỏ và ra ngoài bằng nảy chồi.',
      viewBoxWidth: 560,
      viewBoxHeight: 310,
      durationMs: 14000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 280,
          y: 22,
          text: 'Năm giai đoạn nhân lên của virus trong tế bào chủ',
          size: 14,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'rect',
          id: 'te-bao',
          x: 120,
          y: 140,
          w: 320,
          h: 140,
          rx: 50,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 10000, opacity: 1 },
            { atMs: 10300, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-te-bao',
          x: 280,
          y: 300,
          text: 'tế bào chủ (vi khuẩn)',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 10000, opacity: 1 },
            { atMs: 10300, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-vo',
          x: 280,
          y: 300,
          text: 'tế bào chủ bị phá vỡ (tan)',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 10300, opacity: 0 },
            { atMs: 10600, opacity: 1 },
          ],
        },
        {
          kind: 'polyline',
          id: 'manh-1',
          points: [
            [120, 200],
            [124, 166],
            [146, 145],
            [170, 140],
            [262, 140],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10000, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10300, opacity: 1, dx: -2.5, dy: -2.5 },
            { atMs: 11200, opacity: 1, dx: -10, dy: -10 },
          ],
        },
        {
          kind: 'polyline',
          id: 'manh-2',
          points: [
            [338, 140],
            [390, 140],
            [416, 146],
            [436, 166],
            [440, 228],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10000, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10300, opacity: 1, dx: 3, dy: -2 },
            { atMs: 11200, opacity: 1, dx: 12, dy: -8 },
          ],
        },
        {
          kind: 'polyline',
          id: 'manh-3',
          points: [
            [436, 256],
            [416, 275],
            [390, 280],
            [180, 280],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10000, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10300, opacity: 1, dx: 2, dy: 0.8 },
            { atMs: 11200, opacity: 1, dx: 8, dy: 3 },
          ],
        },
        {
          kind: 'polyline',
          id: 'manh-4',
          points: [
            [146, 275],
            [124, 254],
            [120, 230],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10000, opacity: 0, dx: 0, dy: 0 },
            { atMs: 10300, opacity: 1, dx: -3, dy: 2 },
            { atMs: 11200, opacity: 1, dx: -12, dy: 8 },
          ],
        },
        {
          kind: 'rect',
          id: 'thu-the-1',
          x: 283,
          y: 133,
          w: 10,
          h: 7,
          fill: 'correct',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 10000, opacity: 1 },
            { atMs: 10300, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'thu-the-2',
          x: 307,
          y: 133,
          w: 10,
          h: 7,
          fill: 'correct',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 10000, opacity: 1 },
            { atMs: 10300, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-thu-the',
          x: 330,
          y: 132,
          text: 'thụ thể',
          size: 10,
          anchor: 'start',
          fill: 'muted',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 2600, opacity: 1 },
            { atMs: 2900, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 'phage-dau',
          points: [
            [300, 30],
            [313.9, 38],
            [313.9, 54],
            [300, 62],
            [286.1, 54],
            [286.1, 38],
          ],
          closed: true,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 1,
          keyframes: [
            { atMs: 0, dy: 0, opacity: 1 },
            { atMs: 300, dy: 0, opacity: 1 },
            { atMs: 1800, dy: 38, opacity: 1 },
            { atMs: 3600, dy: 38, opacity: 1 },
            { atMs: 4200, dy: 38, opacity: 0.5 },
            { atMs: 10000, dy: 38, opacity: 0.5 },
            { atMs: 10300, dy: 38, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'phage-duoi',
          x: 296,
          y: 62,
          w: 8,
          h: 30,
          fill: 'primary',
          opacity: 1,
          keyframes: [
            { atMs: 0, dy: 0, opacity: 1 },
            { atMs: 300, dy: 0, opacity: 1 },
            { atMs: 1800, dy: 38, opacity: 1 },
            { atMs: 3600, dy: 38, opacity: 1 },
            { atMs: 4200, dy: 38, opacity: 0.5 },
            { atMs: 10000, dy: 38, opacity: 0.5 },
            { atMs: 10300, dy: 38, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'phage-chan-1',
          x1: 300,
          y1: 92,
          x2: 288,
          y2: 102,
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 1,
          keyframes: [
            { atMs: 0, dy: 0, opacity: 1 },
            { atMs: 300, dy: 0, opacity: 1 },
            { atMs: 1800, dy: 38, opacity: 1 },
            { atMs: 3600, dy: 38, opacity: 1 },
            { atMs: 4200, dy: 38, opacity: 0.5 },
            { atMs: 10000, dy: 38, opacity: 0.5 },
            { atMs: 10300, dy: 38, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'phage-chan-2',
          x1: 300,
          y1: 92,
          x2: 312,
          y2: 102,
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 1,
          keyframes: [
            { atMs: 0, dy: 0, opacity: 1 },
            { atMs: 300, dy: 0, opacity: 1 },
            { atMs: 1800, dy: 38, opacity: 1 },
            { atMs: 3600, dy: 38, opacity: 1 },
            { atMs: 4200, dy: 38, opacity: 0.5 },
            { atMs: 10000, dy: 38, opacity: 0.5 },
            { atMs: 10300, dy: 38, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-phage',
          x: 326,
          y: 50,
          text: 'virus (phage)',
          size: 10,
          anchor: 'start',
          fill: 'muted',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 300, opacity: 1 },
            { atMs: 600, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-vo-rong',
          x: 326,
          y: 80,
          text: 'vỏ capsid rỗng ở ngoài',
          size: 10,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4000, opacity: 0 },
            { atMs: 4300, opacity: 1 },
            { atMs: 6200, opacity: 1 },
            { atMs: 6500, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 'gene-0',
          points: [
            [292, 46],
            [294.7, 43],
            [297.3, 46],
            [300, 49],
            [302.7, 46],
            [305.3, 43],
            [308, 46],
          ],
          stroke: 'warn',
          strokeWidth: 2.5,
          keyframes: [
            { atMs: 0, dy: 0, dx: 0, scale: 1 },
            { atMs: 300, dy: 0, dx: 0, scale: 1 },
            { atMs: 1800, dy: 38, dx: 0, scale: 1 },
            { atMs: 2800, dy: 38, dx: 0, scale: 1 },
            { atMs: 3800, dy: 139, dx: 0, scale: 1.5 },
            { atMs: 7400, dy: 139, dx: 0, scale: 1.5 },
            { atMs: 9000, dy: 194, dx: -10, scale: 0.8 },
            { atMs: 10200, dy: 194, dx: -10, scale: 0.75 },
            { atMs: 11800, dy: 228, dx: 190, scale: 0.75 },
          ],
        },
        {
          kind: 'polyline',
          id: 'gene-1',
          points: [
            [202, 172],
            [204.7, 169],
            [207.3, 172],
            [210, 175],
            [212.7, 172],
            [215.3, 169],
            [218, 172],
          ],
          stroke: 'warn',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 5500, opacity: 0, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 5800, opacity: 1, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 7400, opacity: 1, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 9000, opacity: 1, scale: 0.8, dx: -20, dy: 40 },
            { atMs: 10200, opacity: 1, scale: 0.75, dx: -20, dy: 40 },
            { atMs: 11800, opacity: 1, scale: 0.75, dx: -150, dy: 20 },
          ],
        },
        {
          kind: 'polyline',
          id: 'gene-2',
          points: [
            [344, 258],
            [346.7, 255],
            [349.3, 258],
            [352, 261],
            [354.7, 258],
            [357.3, 255],
            [360, 258],
          ],
          stroke: 'warn',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 6000, opacity: 0, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 6300, opacity: 1, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 7400, opacity: 1, scale: 1.5, dx: 0, dy: 0 },
            { atMs: 9000, opacity: 1, scale: 0.8, dx: 38, dy: -52 },
            { atMs: 10200, opacity: 1, scale: 0.75, dx: 38, dy: -52 },
            { atMs: 11800, opacity: 1, scale: 0.75, dx: 166, dy: -128 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-gene',
          x: 322,
          y: 200,
          text: 'acid nucleic virus',
          size: 10,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3800, opacity: 0 },
            { atMs: 4100, opacity: 1 },
            { atMs: 6200, opacity: 1 },
            { atMs: 6500, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 'dau-moi-1',
          points: [
            [190, 201],
            [199.5, 206.5],
            [199.5, 217.5],
            [190, 223],
            [180.5, 217.5],
            [180.5, 206.5],
          ],
          closed: true,
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 5700, dx: 0, dy: 0, opacity: 0 },
            { atMs: 6000, dx: 0, dy: 0, opacity: 1 },
            { atMs: 10200, dx: 0, dy: 0, opacity: 1 },
            { atMs: 11800, dx: -130, dy: -20, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'duoi-moi-1',
          x: 150,
          y: 196,
          w: 6,
          h: 18,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 6100, opacity: 0, dx: 0, dy: 0 },
            { atMs: 6400, opacity: 1, dx: 0, dy: 0 },
            { atMs: 7600, opacity: 1, dx: 0, dy: 0 },
            { atMs: 9200, opacity: 1, dx: 37, dy: 27 },
            { atMs: 10200, opacity: 1, dx: 37, dy: 27 },
            { atMs: 11800, opacity: 1, dx: -93, dy: 7 },
          ],
        },
        {
          kind: 'polyline',
          id: 'dau-moi-2',
          points: [
            [290, 229],
            [299.5, 234.5],
            [299.5, 245.5],
            [290, 251],
            [280.5, 245.5],
            [280.5, 234.5],
          ],
          closed: true,
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 6100, dx: 0, dy: 0, opacity: 0 },
            { atMs: 6400, dx: 0, dy: 0, opacity: 1 },
            { atMs: 10200, dx: 0, dy: 0, opacity: 1 },
            { atMs: 11800, dx: 200, dy: 34, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'duoi-moi-2',
          x: 232,
          y: 252,
          w: 6,
          h: 18,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 6500, opacity: 0, dx: 0, dy: 0 },
            { atMs: 6800, opacity: 1, dx: 0, dy: 0 },
            { atMs: 7600, opacity: 1, dx: 0, dy: 0 },
            { atMs: 9200, opacity: 1, dx: 55, dy: -1 },
            { atMs: 10200, opacity: 1, dx: 55, dy: -1 },
            { atMs: 11800, opacity: 1, dx: 255, dy: 33 },
          ],
        },
        {
          kind: 'polyline',
          id: 'dau-moi-3',
          points: [
            [390, 195],
            [399.5, 200.5],
            [399.5, 211.5],
            [390, 217],
            [380.5, 211.5],
            [380.5, 200.5],
          ],
          closed: true,
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 6500, dx: 0, dy: 0, opacity: 0 },
            { atMs: 6800, dx: 0, dy: 0, opacity: 1 },
            { atMs: 10200, dx: 0, dy: 0, opacity: 1 },
            { atMs: 11800, dx: 128, dy: -76, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'duoi-moi-3',
          x: 416,
          y: 180,
          w: 6,
          h: 18,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0, dx: 0, dy: 0 },
            { atMs: 6900, opacity: 0, dx: 0, dy: 0 },
            { atMs: 7200, opacity: 1, dx: 0, dy: 0 },
            { atMs: 7600, opacity: 1, dx: 0, dy: 0 },
            { atMs: 9200, opacity: 1, dx: -29, dy: 37 },
            { atMs: 10200, opacity: 1, dx: -29, dy: 37 },
            { atMs: 11800, opacity: 1, dx: 99, dy: -39 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-1',
          x: 12,
          y: 62,
          text: '1. Hấp phụ',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 2300, opacity: 1 },
            { atMs: 2600, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-1-phu',
          x: 12,
          y: 82,
          text: 'gai, sợi đuôi bám đặc hiệu vào thụ thể',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 1,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 2300, opacity: 1 },
            { atMs: 2600, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-2',
          x: 12,
          y: 62,
          text: '2. Xâm nhập',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2600, opacity: 0 },
            { atMs: 2900, opacity: 1 },
            { atMs: 4500, opacity: 1 },
            { atMs: 4800, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-2-phu',
          x: 12,
          y: 82,
          text: 'phage bơm acid nucleic vào trong',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2600, opacity: 0 },
            { atMs: 2900, opacity: 1 },
            { atMs: 4500, opacity: 1 },
            { atMs: 4800, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-3',
          x: 12,
          y: 62,
          text: '3. Sinh tổng hợp',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4800, opacity: 0 },
            { atMs: 5100, opacity: 1 },
            { atMs: 7100, opacity: 1 },
            { atMs: 7400, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-3-phu',
          x: 12,
          y: 82,
          text: 'tế bào chủ làm ra acid nucleic, vỏ protein',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4800, opacity: 0 },
            { atMs: 5100, opacity: 1 },
            { atMs: 7100, opacity: 1 },
            { atMs: 7400, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-4',
          x: 12,
          y: 62,
          text: '4. Lắp ráp',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7400, opacity: 0 },
            { atMs: 7700, opacity: 1 },
            { atMs: 9700, opacity: 1 },
            { atMs: 10000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-4-phu',
          x: 12,
          y: 82,
          text: 'acid nucleic được lồng vào vỏ capsid',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7400, opacity: 0 },
            { atMs: 7700, opacity: 1 },
            { atMs: 9700, opacity: 1 },
            { atMs: 10000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-5',
          x: 12,
          y: 62,
          text: '5. Phóng thích',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 10000, opacity: 0 },
            { atMs: 10300, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gd-5-phu',
          x: 12,
          y: 82,
          text: 'tế bào vỡ, hàng loạt virus mới thoát ra',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 10000, opacity: 0 },
            { atMs: 10300, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 300,
          text: 'Hấp phụ: phage bám đặc hiệu vào thụ thể trên màng, vì vậy mỗi virus chỉ nhiễm một số loại tế bào.',
        },
        {
          atMs: 2600,
          text: 'Xâm nhập: phage bơm acid nucleic vào tế bào, vỏ capsid ở lại bên ngoài.',
        },
        {
          atMs: 4800,
          text: 'Sinh tổng hợp: gene virus bắt bộ máy tế bào chủ làm ra acid nucleic và protein vỏ cho virus.',
        },
        {
          atMs: 7400,
          text: 'Lắp ráp: acid nucleic được lồng vào vỏ capsid, thành hạt virus hoàn chỉnh.',
        },
        {
          atMs: 10000,
          text: 'Phóng thích: tế bào chủ vỡ, hàng loạt virus mới thoát ra (sinh tan); một số virus ra bằng nảy chồi.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 24,
    title: 'Khái quát về virus',
    hook: 'Virus không có cấu tạo tế bào, không thể tự sinh sản hay chuyển hóa năng lượng ở ngoài tế bào chủ. Chúng nằm ở ranh giới giữa vật thể vô sinh và sinh vật sống.',
    theory:
      '## Khái niệm về virus\n' +
      '— Virus là thực thể chưa có cấu tạo tế bào, kích thước siêu hiển vi (dao động từ 10 nm đến 300 nm).\n' +
      '— Ký sinh nội bào bắt buộc: Virus hoàn toàn không có ribosome và các enzyme chuyển hóa vật chất độc lập, chúng chỉ có thể nhân lên bên trong tế bào sống của vật chủ bằng cách sử dụng vật chất và bộ máy sinh tổng hợp của tế bào chủ.\n\n' +
      '## Cấu trúc chung của virus\n' +
      'Mọi virus đều gồm hai thành phần cơ bản:\n' +
      '1. Lõi acid nucleic: Là hệ gene của virus, có thể là DNA hoặc RNA, mạch đơn hoặc mạch kép (khác với sinh vật nhân thực/nhân sơ chỉ có genome DNA mạch kép).\n' +
      '2. Vỏ protein (capsid): Bao bọc lõi acid nucleic, được cấu tạo từ các đơn vị protein gọi là capsomer. Tổ hợp lõi và capsid gọi là nucleocapsid.\n' +
      '— Một số loại virus có thêm vỏ ngoài (envelope): cấu tạo bởi lớp lipid kép tương tự màng sinh chất và các gai glycoprotein nhô ra ngoài, đóng vai trò kháng nguyên giúp hấp phụ đặc hiệu vào tế bào chủ.\n\n' +
      '## Chu trình nhân lên của virus trong tế bào chủ\n' +
      'Gồm 5 giai đoạn liên tiếp:\n' +
      '1. Hấp phụ (Attachment): Gai glycoprotein hoặc protein bề mặt của virus liên kết đặc hiệu với thụ thể trên màng tế bào chủ (như chìa khóa và ổ khóa).\n' +
      '2. Xâm nhập (Entry): Virus đưa toàn bộ hạt virion hoặc chỉ bơm lõi acid nucleic vào bên trong tế bào chất.\n' +
      '3. Sinh tổng hợp (Synthesis): Hệ gene virus điều khiển bộ máy tế bào chủ tổng hợp acid nucleic và các protein vỏ cho virus.\n' +
      '4. Lắp ráp (Assembly): Lõi acid nucleic được lồng vào vỏ capsid để tạo thành các hạt virus mới hoàn chỉnh.\n' +
      '5. Giải phóng (Release): Các virus mới thoát ra ngoài bằng cách phá vỡ làm tan tế bào chủ (chu trình sinh tan - lytic), hoặc nảy chồi qua màng từng hạt một nên tế bào chủ chưa chết ngay. Riêng ở nhiều phage còn có chu trình tiềm tan (lysogenic): hệ gene virus gài vào NST vi khuẩn, nhân đôi cùng tế bào chủ và chưa tạo hạt virus mới.',
    workedExample: {
      problem:
        'Hãy phân biệt sự khác nhau giữa chu trình sinh tan (lytic cycle) và chu trình tiềm tan (lysogenic cycle) của bacteriophage (phage - virus ký sinh vi khuẩn).',
      steps: [
        'So sánh về hành vi của DNA virus sau xâm nhập: Trong chu trình sinh tan, DNA virus nhân lên độc lập lập tức; trong chu trình tiềm tan, DNA virus tích hợp vào nhiễm sắc thể của vi khuẩn tạo thành prophage.',
        'So sánh về số phận của tế bào chủ: Sinh tan làm tan tế bào chủ ngay lập tức giải phóng hàng loạt virus; tiềm tan cho phép tế bào chủ tiếp tục phân đôi bình thường, nhân đôi cả prophage mà không phá hủy tế bào.',
        'Nhận diện sự chuyển đổi: Prophage trong tiềm tan có thể cảm ứng tự phát hoặc do tác nhân ngoài để chuyển sang chu trình sinh tan.',
      ],
      answer:
        'Chu trình sinh tan phá hủy tế bào chủ để giải phóng hạt virus mới; chu trình tiềm tan tích hợp hệ gene virus vào NST tế bào chủ để cùng nhân đôi và không phá hủy tế bào ngay.',
    },
    checkQuestions: [
      {
        prompt: 'Thành phần cấu tạo nào sau đây có ở tất cả các loại virus?',
        choices: [
          { id: 'vr_1', label: 'Vỏ ngoài bằng lipid kép' },
          { id: 'vr_2', label: 'Lõi acid nucleic và vỏ capsid protein' },
          { id: 'vr_3', label: 'Hệ bào quan ti thể và ribosome' },
          { id: 'vr_4', label: 'Thành peptidoglycan vững chắc' },
        ],
        answer: { kind: 'choice', correctIds: ['vr_2'] },
        explain:
          'Tất cả các loại virus tối thiểu đều phải có lõi chứa acid nucleic (vật chất di truyền) và lớp vỏ capsid bằng protein bảo vệ bên ngoài. Vỏ ngoài lipid chỉ có ở một số nhóm virus nhất định.',
      },
      {
        prompt: 'Tại sao virus không thể tự nhân đôi ngoài tế bào chủ?',
        choices: [
          {
            id: 'vrc_1',
            label:
              'Vì chúng không có ribosome và các enzyme cần thiết cho sự tự sinh tổng hợp chất',
          },
          {
            id: 'vrc_2',
            label: 'Vì cấu trúc acid nucleic của chúng bị phân hủy ngay khi ra ngoài không khí',
          },
          { id: 'vrc_3', label: 'Vì vỏ capsid ngăn cản mọi phản ứng hóa học xảy ra' },
          { id: 'vrc_4', label: 'Vì chúng chỉ sống được trong môi trường không có oxy' },
        ],
        answer: { kind: 'choice', correctIds: ['vrc_1'] },
        explain:
          'Virus là thực thể chưa có cấu tạo tế bào, thiếu hoàn toàn ribosome (bộ máy dịch mã tổng hợp protein) và các hệ enzyme chuyển hóa năng lượng, do đó không thể tự nhân lên nếu không ký sinh nội bào bắt buộc.',
      },
    ],
    srsCards: [
      {
        hoi: 'Hạt nucleocapsid của virus gồm những thành phần nào?',
        dap: 'Lõi acid nucleic (DNA hoặc RNA) kết hợp với vỏ protein (capsid).',
      },
      {
        hoi: 'Bacteriophage (phage) là gì?',
        dap: 'Là nhóm virus chuyên ký sinh và phá hủy các tế bào vi khuẩn.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c8-b25',
    animation: {
      title: 'Đáp ứng miễn dịch sơ cấp và thứ cấp sau tiêm vaccine',
      description:
        'Đường nồng độ kháng thể trong máu vẽ theo thời gian qua hai lần tiếp xúc với kháng nguyên. Lần tiếp xúc thứ nhất cho ĐÁP ỨNG SƠ CẤP: phải mất khoảng một đến hai tuần kháng thể mới bắt đầu tăng, đỉnh thấp, rồi giảm dần — trong khoảng trễ đó cơ thể chưa được bảo vệ. Lần tiếp xúc thứ hai, nhờ đã có tế bào nhớ, cho ĐÁP ỨNG THỨ CẤP: kháng thể tăng chỉ sau vài ngày, đỉnh cao hơn nhiều lần và duy trì lâu hơn hẳn. Điều chỉ hình động nói rõ được: mũi tiêm nhắc lại không phải là làm lại mũi cũ cho chắc, mà là khai thác trí nhớ miễn dịch để tạo một đường cong khác hẳn về cả tốc độ, độ cao lẫn độ bền.',
      viewBoxWidth: 480,
      viewBoxHeight: 272,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 240,
          y: 20,
          text: 'Vì sao phải tiêm nhắc lại',
          size: 15,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'line',
          id: 'truc-x',
          x1: 62,
          y1: 236,
          x2: 452,
          y2: 236,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'truc-y',
          x1: 62,
          y1: 236,
          x2: 62,
          y2: 44,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-x',
          x: 452,
          y: 258,
          text: 'Thời gian (tuần)',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-y',
          x: 56,
          y: 40,
          text: 'Nồng độ kháng thể',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'line',
          id: 'gd0',
          x1: 93.2,
          y1: 236,
          x2: 93.2,
          y2: 44,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 4',
        },
        {
          kind: 'line',
          id: 'gd1',
          x1: 264.8,
          y1: 236,
          x2: 264.8,
          y2: 44,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 4',
        },
        {
          kind: 'polyline',
          id: 'duong0',
          points: [
            [62, 232.2],
            [93.2, 232.2],
            [116.6, 224.5],
            [140, 201.4],
            [163.4, 186.1],
            [186.8, 193.8],
            [218, 207.2],
            [249.2, 216.8],
            [264.8, 218.7],
            [280.4, 197.6],
            [296, 130.4],
            [311.6, 78.6],
            [327.2, 57.4],
            [350.6, 63.2],
            [381.8, 78.6],
            [413, 93.9],
            [452, 109.3],
          ],
          stroke: 'primary',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 0 },
            { atMs: 900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'cham-chay',
          cx: 62,
          cy: 232.2,
          r: 6,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 900, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1360, dx: 31.2, dy: 0, opacity: 1 },
            { atMs: 1820, dx: 54.6, dy: -7.7, opacity: 1 },
            { atMs: 2280, dx: 78, dy: -30.8, opacity: 1 },
            { atMs: 2740, dx: 101.4, dy: -46.1, opacity: 1 },
            { atMs: 3200, dx: 124.8, dy: -38.4, opacity: 1 },
            { atMs: 3660, dx: 156, dy: -25, opacity: 1 },
            { atMs: 4120, dx: 187.2, dy: -15.4, opacity: 1 },
            { atMs: 4580, dx: 218.4, dy: -34.6, opacity: 1 },
            { atMs: 5040, dx: 234, dy: -101.8, opacity: 1 },
            { atMs: 5500, dx: 249.6, dy: -153.6, opacity: 1 },
            { atMs: 5960, dx: 265.2, dy: -174.8, opacity: 1 },
            { atMs: 6420, dx: 288.6, dy: -169, opacity: 1 },
            { atMs: 6880, dx: 319.8, dy: -153.6, opacity: 1 },
            { atMs: 7340, dx: 351, dy: -138.3, opacity: 1 },
            { atMs: 7800, dx: 390, dy: -122.9, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc0',
          x: 101,
          y: 62,
          text: 'Mũi 1',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1200, opacity: 0 },
            { atMs: 1500, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc1',
          x: 150,
          y: 176,
          text: 'Sơ cấp: chậm, thấp',
          size: 12,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2700, opacity: 0 },
            { atMs: 3000, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc2',
          x: 257,
          y: 62,
          text: 'Mũi nhắc lại',
          size: 12,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'gc3',
          x: 452,
          y: 50,
          text: 'Thứ cấp: nhanh, cao, bền',
          size: 12,
          anchor: 'end',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5900, opacity: 0 },
            { atMs: 6200, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
      ],
      captions: [
        { atMs: 1500, text: 'Lần tiếp xúc kháng nguyên thứ nhất.' },
        {
          atMs: 3000,
          text: 'Đáp ứng sơ cấp: mất 1–2 tuần mới tăng, đỉnh thấp, rồi giảm — trong khoảng trễ đó chưa được bảo vệ.',
        },
        {
          atMs: 4600,
          text: 'Mũi tiêm nhắc lại gặp lại kháng nguyên cũ, lúc này đã có tế bào nhớ.',
        },
        {
          atMs: 6200,
          text: 'Đáp ứng thứ cấp: tăng sau vài ngày, đỉnh cao hơn nhiều lần và duy trì lâu hơn hẳn.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 25,
    title: 'Một số bệnh do virus và các thành tựu nghiên cứu ứng dụng virus',
    hook: 'Từ các bệnh cúm mùa, sốt xuất huyết, đến đại dịch COVID-19 nguy hiểm, virus đã gây tổn thất khổng lồ cho nhân loại. Tuy nhiên, chúng ta cũng đang ứng dụng chính cấu trúc đặc biệt của chúng để cứu người.',
    theory:
      '## Các bệnh truyền nhiễm do virus gây ra ở người\n' +
      '— Lây qua đường hô hấp: Cúm, Sởi, COVID-19, Thủy đậu.\n' +
      '— Lây qua đường tiêu hóa: Tiêu chảy cấp do Rotavirus, viêm gan A.\n' +
      '— Lây qua đường máu, quan hệ tình dục, từ mẹ sang con: HIV/AIDS, viêm gan B, viêm gan C.\n' +
      '— Lây qua vết cắn của vật trung gian (véc tơ): Sốt xuất huyết (muỗi vằn lây truyền virus Dengue), bệnh Dại (chó, mèo mang virus dại truyền qua vết cắn).\n\n' +
      '## Cơ chế phòng chống bệnh do virus\n' +
      '— Sử dụng Vaccine: Biện pháp hiệu quả nhất để chủ động phòng bệnh. Vaccine kích thích cơ thể sinh kháng thể và tế bào nhớ miễn dịch chống lại virus khi có sự xâm nhiễm thực tế.\n' +
      '— Không dùng thuốc kháng sinh điều trị bệnh do virus vì kháng sinh chỉ tác động lên các đích đặc hiệu của vi khuẩn (như tổng hợp vách peptidoglycan, ribosome nhân sơ...).\n\n' +
      '## Ứng dụng của virus trong y học và đời sống\n' +
      '1. Sản xuất chế phẩm sinh học (interferon, hormone insulin): Sử dụng phage làm vectơ chuyển gene mong muốn vào vi khuẩn để sản xuất số lượng lớn.\n' +
      '2. Liệu pháp gene (Gene therapy): Dùng virus đã được vô hiệu hóa khả năng gây độc làm phương tiện vận chuyển đưa gene lành tích hợp vào hệ gene người bệnh nhằm sửa chữa các lỗi di truyền.\n' +
      '3. Sản xuất thuốc trừ sâu sinh học: Sử dụng các virus diệt côn trùng hại (như Baculovirus) để phun cho cây trồng, an toàn với môi trường và sức khỏe con người.',
    workedExample: {
      problem:
        'Giải thích tại sao chúng ta không thể sử dụng thuốc kháng sinh để tiêu diệt virus gây bệnh cúm ở người.',
      steps: [
        'Xem xét cơ chế tác dụng của thuốc kháng sinh: Tấn công các cấu trúc đặc thù của tế bào vi khuẩn (thành peptidoglycan, màng sinh chất, ribosome 70S...).',
        'Xem xét cấu tạo của virus cúm: Không có cấu trúc tế bào, không thành peptidoglycan, không ribosome riêng.',
        'Kết luận: Kháng sinh hoàn toàn không có điểm đích tác động trên hạt virus, do đó không tiêu diệt được virus cúm.',
      ],
      answer:
        'Kháng sinh tấn công cấu trúc tế bào đặc trưng của vi khuẩn, trong khi virus không có cấu tạo tế bào nên kháng sinh không có tác dụng.',
    },
    checkQuestions: [
      {
        prompt:
          'Biện pháp nào sau đây là hiệu quả nhất để phòng tránh chủ động các bệnh truyền nhiễm nguy hiểm do virus ở người?',
        choices: [
          { id: 'pv_1', label: 'Tiêm phòng vaccine đầy đủ và đúng lịch' },
          { id: 'pv_2', label: 'Uống thuốc kháng sinh liều cao hàng ngày' },
          { id: 'pv_3', label: 'Chỉ ăn thức ăn chín và uống nước sôi' },
          { id: 'pv_4', label: 'Tránh tiếp xúc hoàn toàn với ánh nắng mặt trời' },
        ],
        answer: { kind: 'choice', correctIds: ['pv_1'] },
        explain:
          'Tiêm vaccine giúp hệ miễn dịch nhận diện trước kháng nguyên của virus, sinh kháng thể và tế bào nhớ miễn dịch trước khi gặp virus thật, nhờ đó phòng bệnh một cách chủ động.',
      },
      {
        prompt:
          'Ứng dụng nào sau đây sử dụng virus làm vectơ chuyển gene lành thay thế gene bệnh ở tế bào người?',
        choices: [
          { id: 'lh_1', label: 'Liệu pháp gene (Gene therapy)' },
          { id: 'lh_2', label: 'Sản xuất thuốc trừ sâu sinh học' },
          { id: 'lh_3', label: 'Lên men sữa chua' },
          { id: 'lh_4', label: 'Phage trị liệu diệt vi khuẩn tả' },
        ],
        answer: { kind: 'choice', correctIds: ['lh_1'] },
        explain:
          'Liệu pháp gene sử dụng virus làm vectơ vận chuyển (vector) để đưa gene lành vào tế bào của bệnh nhân bị đột biến gene nhằm sửa chữa lỗi di truyền.',
      },
    ],
    srsCards: [
      {
        hoi: 'Virus Dengue gây bệnh sốt xuất huyết lây truyền qua con đường nào?',
        dap: 'Lây truyền ngang qua vết đốt của vật trung gian truyền bệnh là muỗi vằn (Aedes aegypti).',
      },
      {
        hoi: 'Tại sao không dùng kháng sinh để trị bệnh cúm?',
        dap: 'Vì kháng sinh chỉ có tác dụng tiêu diệt hoặc ức chế vi khuẩn; virus không có cấu tạo tế bào nên không bị kháng sinh tác động.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c8-b26',
    animation: {
      title: 'Tỉ lệ hormone quyết định mô sẹo ra chồi hay ra rễ',
      description:
        'Một khối mô sẹo (callus) nằm trên môi trường nuôi cấy, bên phải là hai cột biểu diễn lượng cytokinin và auxin trong môi trường. Lúc đầu hai cột cao ngang nhau: tỉ lệ cân bằng chỉ làm mô sẹo phân chia, lớn lên thành khối tế bào chưa phân hoá. Tăng cytokinin cao hơn auxin thì từ mô sẹo mọc ra chồi và lá. Đảo lại, auxin cao hơn cytokinin thì mô sẹo ra rễ. Cây con có đủ chồi và rễ được đem ra vườn ươm huấn luyện. Điều hình động cho thấy rõ: người làm nuôi cấy mô không "gắn" chồi hay rễ vào mẫu, mà chỉ đổi tỉ lệ hai hormone trong môi trường; các tế bào mô sẹo mang đủ thông tin di truyền của loài (tính toàn năng) sẽ tự biệt hoá theo tín hiệu đó.',
      viewBoxWidth: 460,
      viewBoxHeight: 240,
      durationMs: 12000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 230,
          y: 22,
          text: 'Mô sẹo: tỉ lệ cytokinin/auxin quyết định hướng phát triển',
          size: 13,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'rect',
          id: 'moi-truong',
          x: 110,
          y: 166,
          w: 240,
          h: 50,
          rx: 6,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'lb-mt',
          x: 230,
          y: 232,
          text: 'môi trường nuôi cấy',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'choi1',
          points: [
            [216, 128],
            [210, 94],
            [200, 80],
          ],
          stroke: 'correct',
          strokeWidth: 4,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2600, opacity: 0 },
            { atMs: 3600, opacity: 1 },
            { atMs: 5000, opacity: 1 },
            { atMs: 5600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 'choi2',
          points: [
            [232, 126],
            [234, 86],
            [244, 70],
          ],
          stroke: 'correct',
          strokeWidth: 4,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2800, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 5000, opacity: 1 },
            { atMs: 5600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'la1',
          cx: 198,
          cy: 78,
          r: 7,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3200, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 5000, opacity: 1 },
            { atMs: 5600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'la2',
          cx: 246,
          cy: 68,
          r: 7,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3400, opacity: 0 },
            { atMs: 4000, opacity: 1 },
            { atMs: 5000, opacity: 1 },
            { atMs: 5600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 're1',
          points: [
            [214, 168],
            [206, 194],
            [196, 208],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 8000, opacity: 1 },
            { atMs: 10400, opacity: 1 },
            { atMs: 11000, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 're2',
          points: [
            [230, 172],
            [232, 202],
            [226, 214],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7200, opacity: 0 },
            { atMs: 8200, opacity: 1 },
            { atMs: 10400, opacity: 1 },
            { atMs: 11000, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'polyline',
          id: 're3',
          points: [
            [246, 168],
            [256, 192],
            [266, 204],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7400, opacity: 0 },
            { atMs: 8400, opacity: 1 },
            { atMs: 10400, opacity: 1 },
            { atMs: 11000, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'mo-seo',
          cx: 230,
          cy: 150,
          r: 26,
          fill: 'accent',
          keyframes: [
            { atMs: 0, scale: 0.7 },
            { atMs: 1600, scale: 1 },
            { atMs: 12000, scale: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-ms',
          x: 230,
          y: 110,
          text: 'mô sẹo',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 0, opacity: 0 },
            { atMs: 300, opacity: 1 },
            { atMs: 2400, opacity: 1 },
            { atMs: 2800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'cot-cyto',
          x: 366,
          y: 120,
          w: 26,
          h: 90,
          rx: 4,
          fill: 'correct',
          origin: [379, 210],
          keyframes: [
            { atMs: 0, scaleY: 0.5 },
            { atMs: 1600, scaleY: 0.5 },
            { atMs: 2400, scaleY: 0.9 },
            { atMs: 5200, scaleY: 0.9 },
            { atMs: 6200, scaleY: 0.3 },
            { atMs: 10400, scaleY: 0.3 },
            { atMs: 11200, scaleY: 0.5 },
            { atMs: 12000, scaleY: 0.5 },
          ],
        },
        {
          kind: 'rect',
          id: 'cot-aux',
          x: 414,
          y: 120,
          w: 26,
          h: 90,
          rx: 4,
          fill: 'primary',
          origin: [427, 210],
          keyframes: [
            { atMs: 0, scaleY: 0.5 },
            { atMs: 1600, scaleY: 0.5 },
            { atMs: 2400, scaleY: 0.3 },
            { atMs: 5200, scaleY: 0.3 },
            { atMs: 6200, scaleY: 0.9 },
            { atMs: 10400, scaleY: 0.9 },
            { atMs: 11200, scaleY: 0.5 },
            { atMs: 12000, scaleY: 0.5 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-cyto',
          x: 379,
          y: 226,
          text: 'cytokinin',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'lb-aux',
          x: 427,
          y: 226,
          text: 'auxin',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'pha1',
          x: 70,
          y: 70,
          text: 'cân bằng:',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 300, opacity: 0 },
            { atMs: 800, opacity: 1 },
            { atMs: 2200, opacity: 1 },
            { atMs: 2600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'pha1b',
          x: 70,
          y: 88,
          text: 'chỉ phân chia',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 300, opacity: 0 },
            { atMs: 800, opacity: 1 },
            { atMs: 2200, opacity: 1 },
            { atMs: 2600, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'pha2',
          x: 70,
          y: 70,
          text: 'cytokinin > auxin:',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2600, opacity: 0 },
            { atMs: 3200, opacity: 1 },
            { atMs: 5200, opacity: 1 },
            { atMs: 5800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'pha2b',
          x: 70,
          y: 88,
          text: 'ra CHỒI',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2600, opacity: 0 },
            { atMs: 3200, opacity: 1 },
            { atMs: 5200, opacity: 1 },
            { atMs: 5800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'pha3',
          x: 70,
          y: 70,
          text: 'auxin > cytokinin:',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6400, opacity: 0 },
            { atMs: 7000, opacity: 1 },
            { atMs: 10400, opacity: 1 },
            { atMs: 11000, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'pha3b',
          x: 70,
          y: 88,
          text: 'ra RỄ',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6400, opacity: 0 },
            { atMs: 7000, opacity: 1 },
            { atMs: 10400, opacity: 1 },
            { atMs: 11000, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
      ],
      captions: [
        {
          atMs: 300,
          text: 'Tỉ lệ auxin và cytokinin cân bằng: mô sẹo chỉ phân chia, lớn thành khối tế bào chưa phân hoá.',
        },
        { atMs: 2600, text: 'Tăng cytokinin cao hơn auxin: từ mô sẹo mọc ra chồi và lá.' },
        { atMs: 6400, text: 'Đảo lại, auxin cao hơn cytokinin: mô sẹo ra rễ.' },
        {
          atMs: 9000,
          text: 'Chỉ đổi tỉ lệ hormone trong môi trường — tế bào toàn năng tự biệt hoá theo tín hiệu đó.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 26,
    title:
      'Thực hành: Điều tra một số bệnh do virus gây ra và nhân giống cây trồng bằng nuôi cấy mô',
    hook: 'Làm thế nào để điều tra dịch tễ học về tình hình bệnh truyền nhiễm do virus ở trường học hoặc địa phương? Và làm sao nhân bản hàng ngàn cây lan quý từ một đỉnh sinh trưởng nhỏ bé?',
    theory:
      '## Điều tra bệnh truyền nhiễm do virus gây ra\n' +
      '— Phương pháp dịch tễ cơ bản: Thiết kế phiếu khảo sát, thu thập số liệu từ trạm y tế địa phương, trường học, hộ gia đình về số ca mắc, đối tượng mắc, triệu chứng và đường lây nhiễm.\n' +
      '— Mục tiêu: Đánh giá thực trạng dịch bệnh, vẽ biểu đồ diễn biến ca bệnh theo thời gian, đề xuất các khuyến nghị vệ sinh dịch tễ phù hợp.\n\n' +
      '## Kỹ thuật nhân giống cây trồng bằng nuôi cấy mô (tế bào thực vật)\n' +
      'Dựa trên tính toàn năng của tế bào thực vật: Mỗi tế bào sống đều mang toàn bộ lượng thông tin di truyền của loài, trong điều kiện thích hợp có thể phản biệt hóa rồi tái biệt hóa để hình thành cây con hoàn chỉnh.\n' +
      '— Quy trình nhân giống cơ bản:\n' +
      '  1. Chọn và khử trùng mẫu cấy (thường lấy đỉnh sinh trưởng chứa tế bào phân sinh sạch virus).\n' +
      '  2. Nuôi cấy cảm ứng tạo Callus (mô sẹo): Dùng môi trường dinh dưỡng bổ sung auxin và cytokinin ở tỉ lệ cân bằng.\n' +
      '  3. Kích thích phát triển chồi: Tăng tỉ lệ hormone Cytokinin so với Auxin.\n' +
      '  4. Kích thích ra rễ: Tăng tỉ lệ hormone Auxin so với Cytokinin.\n' +
      '  5. Huấn luyện cây con ngoài vườn ươm trước khi đưa ra trồng đại trà.\n' +
      '— Ý nghĩa: Tạo ra lượng lớn cây con sạch bệnh, đồng đều về mặt di truyền, bảo tồn nguồn gene thực vật quý hiếm.',
    workedExample: {
      problem:
        'Trong môi trường nuôi cấy mô tế bào thực vật (Callus), để điều khiển mô sẹo phát triển ra rễ hoặc ra chồi, người ta điều chỉnh tỉ lệ của hai loại hormone nào?',
      steps: [
        'Xác định hai loại hormone sinh trưởng thực vật chủ đạo trong nuôi cấy mô là Auxin (kích thích phân chia và ra rễ) và Cytokinin (kích thích phân chia và biệt hóa chồi).',
        'Nếu muốn kích thích tạo chồi: Tăng nồng độ Cytokinin cao hơn Auxin.',
        'Nếu muốn kích thích ra rễ: Tăng nồng độ Auxin cao hơn Cytokinin.',
      ],
      answer: 'Điều chỉnh tỉ lệ hormone Auxin (ra rễ) và Cytokinin (ra chồi).',
    },
    checkQuestions: [
      {
        prompt:
          'Hiện tượng mô sẹo (callus) hình thành chồi hay rễ phụ thuộc chủ yếu vào sự điều hòa tỉ lệ giữa hai nhóm hormone nào?',
        choices: [
          { id: 'hm_1', label: 'Auxin và Cytokinin' },
          { id: 'hm_2', label: 'Ethylene và Abscisic acid' },
          { id: 'hm_3', label: 'Gibberellin và Ethylene' },
          { id: 'hm_4', label: 'Auxin và Gibberellin' },
        ],
        answer: { kind: 'choice', correctIds: ['hm_1'] },
        explain:
          'Sự tương tác tỉ lệ giữa Auxin và Cytokinin là nhân tố quyết định hướng biệt hóa mô sẹo thực vật trong nuôi cấy mô tế bào.',
      },
      {
        prompt:
          'Ý nghĩa thực tiễn nổi bật nhất của phương pháp nhân giống vô tính bằng nuôi cấy mô tế bào thực vật là gì?',
        choices: [
          {
            id: 'yn_1',
            label: 'Tạo ra số lượng lớn cây con đồng đều, sạch bệnh từ một mẫu mô nhỏ ban đầu',
          },
          { id: 'yn_2', label: 'Tăng cường tần số đột biến tạo ra nhiều giống hoa mới lạ' },
          {
            id: 'yn_3',
            label: 'Rút ngắn thời gian sinh trưởng sinh dưỡng để cây ra quả ngay lập tức',
          },
          { id: 'yn_4', label: 'Làm biến đổi bộ NST lưỡng bội thành đa bội' },
        ],
        answer: { kind: 'choice', correctIds: ['yn_1'] },
        explain:
          'Nuôi cấy mô tế bào cho phép nhân giống vô tính nhanh chóng, tạo hàng loạt cây con có kiểu gene đồng nhất với cây mẹ ban đầu và có thể chọn mẫu sạch virus để sản xuất giống sạch bệnh.',
      },
    ],
    srsCards: [
      {
        hoi: 'Tỉ lệ Cytokinin / Auxin thế nào sẽ kích thích mô sẹo thực vật phát triển thành chồi?',
        dap: 'Tỉ lệ Cytokinin / Auxin cao (Cytokinin nhiều hơn Auxin).',
      },
      {
        hoi: 'Nguyên lí sinh học cốt lõi của nuôi cấy mô tế bào thực vật là gì?',
        dap: 'Tính toàn năng của tế bào thực vật (totipotency) và khả năng phản biệt hóa, tái biệt hóa của chúng.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
