// lessons/sinh10c3.ts — Sinh học 10, Chương 4 & 5 (Bài 13-19).
import type { BiologyLesson } from '../lessonTypes.js'

export const SINH10_C3_LESSONS: BiologyLesson[] = [
  {
    id: 'sinh10-c5-b13',
    animation: {
      title: 'ATP — đồng tiền năng lượng nạp và tiêu liên tục',
      description:
        'Hai mũi tên nối ADP + Pi với ATP thành một vòng khép kín, chấm sáng chạy vòng quanh không ngừng. Mũi tên trên: năng lượng giải phóng từ DỊ HOÁ (phân giải chất hữu cơ) được dùng để gắn thêm một nhóm phosphate vào ADP, tạo ATP — nạp tiền vào ví. Mũi tên dưới: ATP bị thuỷ phân, cắt liên kết cao năng giữa hai nhóm phosphate cuối, giải phóng khoảng 30,5 kJ mỗi mol để chạy các việc tốn năng lượng như tổng hợp chất, co cơ, vận chuyển chủ động, rồi trở lại thành ADP. Điều hình động phá được: ATP không phải kho dự trữ lâu dài mà là tiền lẻ tiêu ngay — một phân tử ATP quay vòng nhiều lần trong một ngày, nên tế bào phải tái tạo nó liên tục.',
      viewBoxWidth: 420,
      viewBoxHeight: 250,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'o-adp',
          x: 22,
          y: 106,
          w: 104,
          h: 48,
          rx: 10,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'l-adp',
          x: 74,
          y: 136,
          text: 'ADP + Pi',
          size: 15,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'rect',
          id: 'o-atp',
          x: 294,
          y: 106,
          w: 104,
          h: 48,
          rx: 10,
          fill: 'surface',
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'l-atp',
          x: 346,
          y: 136,
          text: 'ATP',
          size: 16,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'arrow',
          id: 'nap',
          x1: 132,
          y1: 116,
          x2: 290,
          y2: 116,
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'arrow',
          id: 'tieu',
          x1: 290,
          y1: 144,
          x2: 132,
          y2: 144,
          stroke: 'accent',
          strokeWidth: 3,
        },
        {
          kind: 'label',
          id: 'l-nap',
          x: 210,
          y: 100,
          text: 'Dị hoá giải phóng năng lượng → nạp ATP',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'l-tieu',
          x: 210,
          y: 174,
          text: 'Thuỷ phân ATP ≈ 30,5 kJ/mol → co cơ, tổng hợp chất',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'chay',
          cx: 136,
          cy: 116,
          r: 7,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 148, dy: 0 },
            { atMs: 3400, dx: 148, dy: 0 },
            { atMs: 4400, dx: 148, dy: 28 },
            { atMs: 6800, dx: 0, dy: 28 },
            { atMs: 7500, dx: 0, dy: 0 },
            { atMs: 8000, dx: 0, dy: 0 },
          ],
        },
      ],
      captions: [
        { atMs: 300, text: 'Bắt đầu từ ADP và nhóm phosphate tự do.' },
        {
          atMs: 2000,
          text: 'Phản ứng dị hoá giải phóng năng lượng, gắn thêm phosphate vào ADP để tạo ATP.',
        },
        { atMs: 4000, text: 'ATP là dạng năng lượng sẵn dùng của tế bào.' },
        {
          atMs: 5600,
          text: 'Thuỷ phân liên kết cao năng, giải phóng ≈ 30,5 kJ/mol cho co cơ, tổng hợp chất, vận chuyển chủ động.',
        },
        {
          atMs: 7200,
          text: 'Quay lại ADP: ATP là tiền lẻ tiêu ngay, quay vòng liên tục chứ không phải kho dự trữ.',
        },
      ],
    },
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 13,
    title: 'Khái quát về chuyển hoá vật chất và năng lượng',
    hook: 'Ngay cả khi ngủ, cơ thể bạn vẫn tiêu thụ năng lượng. Tế bào không bao giờ nghỉ ngơi — chúng không ngừng chuyển hoá năng lượng từ thức ăn thành ATP để duy trì sự sống.',
    theory:
      '## Chuyển hoá vật chất và năng lượng\n' +
      '— Chuyển hoá (Metabolism): Toàn bộ các phản ứng hoá học xảy ra trong tế bào và cơ thể sống.\n' +
      '— Hai quá trình đối lập:\n' +
      '  1. Đồng hoá (Anabolism): Tổng hợp các phân tử phức tạp từ phân tử đơn giản. Cần năng lượng ATP. Ví dụ: quang hợp, tổng hợp protein.\n' +
      '  2. Dị hoá (Catabolism): Phân giải các phân tử phức tạp thành phân tử đơn giản. Giải phóng năng lượng ATP. Ví dụ: hô hấp tế bào.\n\n' +
      '## Enzyme (enzym) và vai trò xúc tác\n' +
      '— Enzyme là chất xúc tác sinh học, bản chất là protein (một số là RNA - ribozyme).\n' +
      '— Đặc điểm:\n' +
      '  + Xúc tác đặc hiệu: Mỗi enzyme chỉ xúc tác một hoặc một số phản ứng nhất định.\n' +
      '  + Tăng tốc độ phản ứng mà không bị tiêu hao.\n' +
      '  + Hoạt động phụ thuộc nhiệt độ, pH, nồng độ cơ chất.\n' +
      '— Cơ chế: Enzyme gắn với cơ chất (substrate) tại trung tâm hoạt động (active site), tạo phức enzyme-cơ chất, thực hiện phản ứng, rồi giải phóng sản phẩm.\n' +
      '— ATP (Adenosine Triphosphate): Là đơn vị năng lượng phổ quát của tế bào. Năng lượng được lưu trong liên kết phosphate cao năng.',
    workedExample: {
      problem:
        'Giải thích tại sao enzyme amylase trong nước bọt chỉ phân giải tinh bột mà không phân giải protein thịt.',
      steps: [
        'Enzyme amylase có trung tâm hoạt động (active site) với hình dạng không gian đặc trưng.',
        'Chỉ có phân tử tinh bột (cơ chất đặc hiệu) mới có hình dạng phù hợp để gắn khít vào trung tâm hoạt động của amylase (giống khóa và chìa).',
        'Phân tử protein có hình dạng khác, không thể gắn vào trung tâm hoạt động của amylase, do đó không bị amylase xúc tác phân giải.',
      ],
      answer:
        'Enzyme có tính đặc hiệu cao: trung tâm hoạt động của amylase chỉ khớp với tinh bột, không khớp với protein.',
    },
    checkQuestions: [
      {
        prompt: 'Quá trình đồng hoá (Anabolism) trong tế bào có đặc điểm là:',
        choices: [
          { id: 'dh_1', label: 'Tổng hợp phân tử phức tạp từ đơn giản, cần tiêu tốn năng lượng' },
          { id: 'dh_2', label: 'Phân giải phân tử phức tạp thành đơn giản, giải phóng năng lượng' },
          { id: 'dh_3', label: 'Không liên quan đến ATP' },
          { id: 'dh_4', label: 'Chỉ xảy ra ở thực vật' },
        ],
        answer: { kind: 'choice', correctIds: ['dh_1'] },
        explain: 'Đồng hoá là tổng hợp, cần ATP (ví dụ: quang hợp, tổng hợp protein).',
      },
      {
        prompt: 'Đặc điểm nào sau đây KHÔNG đúng với enzyme?',
        choices: [
          { id: 'ez_1', label: 'Enzyme bị tiêu hao sau mỗi phản ứng mà nó xúc tác' },
          { id: 'ez_2', label: 'Enzyme có tính đặc hiệu cao với cơ chất' },
          { id: 'ez_3', label: 'Enzyme làm tăng tốc độ phản ứng hoá học' },
          { id: 'ez_4', label: 'Enzyme bản chất là protein' },
        ],
        answer: { kind: 'choice', correctIds: ['ez_1'] },
        explain:
          'Enzyme là chất xúc tác sinh học, không bị tiêu hao sau phản ứng và có thể tái sử dụng nhiều lần.',
      },
    ],
    srsCards: [
      {
        hoi: 'ATP là gì và vai trò của nó trong tế bào?',
        dap: 'ATP (Adenosine Triphosphate) là đơn vị năng lượng phổ quát của tế bào, dự trữ năng lượng trong liên kết phosphate cao năng.',
      },
      {
        hoi: 'Phân biệt đồng hoá và dị hoá?',
        dap: 'Đồng hoá: tổng hợp phân tử phức tạp, cần ATP. Dị hoá: phân giải phân tử phức tạp, giải phóng ATP.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c5-b14',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 14,
    title: 'Phân giải và tổng hợp các chất trong tế bào',
    hook: 'Khi bạn chạy bộ, cơ thể đốt cháy glucose và mỡ để lấy năng lượng. Khi bạn ngủ, cơ thể dùng năng lượng đó để tổng hợp protein phục hồi cơ. Hai quá trình này — hô hấp tế bào và quang hợp — là trụ cột của sự sống.',
    theory:
      '## Hô hấp tế bào (cellular respiration)\n' +
      '— Phương trình tổng quát: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Năng lượng (ATP + Nhiệt).\n' +
      '— Ba giai đoạn chính:\n' +
      '  1. Đường phân (Glycolysis): Xảy ra trong tế bào chất. Glucose (6C) → 2 Pyruvate (3C) + 2 ATP + 2 NADH.\n' +
      '  2. Chu trình Krebs (Citric acid cycle): Xảy ra trong chất nền ty thể. Pyruvate → CO₂ + ATP + NADH + FADH₂.\n' +
      '  3. Chuỗi chuyền điện tử (Electron Transport Chain): Xảy ra trên màng trong ty thể. NADH/FADH₂ → khoảng 26-28 ATP + H₂O.\n\n' +
      'QUANG HỢP (PHOTOSYNTHESIS) - Chỉ ở sinh vật có lục lạp:\n' +
      '— Phương trình tổng quát: 6CO₂ + 6H₂O + Ánh sáng → C₆H₁₂O₆ + 6O₂.\n' +
      '— Hai giai đoạn:\n' +
      '  1. Pha sáng (Light reactions): Xảy ra trên màng thylakoid. Ánh sáng phân li H₂O, giải phóng O₂, tổng hợp ATP và NADPH.\n' +
      '  2. Pha tối/Chu trình Calvin (Dark reactions/Calvin cycle): Xảy ra trong chất nền lục lạp (stroma). CO₂ + ATP + NADPH → Glucose.',
    workedExample: {
      problem:
        'Tính số phân tử ATP tối đa có thể tổng hợp được từ 1 phân tử glucose qua hô hấp hiếu khí.',
      steps: [
        'Đường phân: thu lãi 2 ATP.',
        'Chu trình Krebs: thu thêm 2 ATP.',
        'Chuỗi chuyền điện tử: khoảng 26-28 ATP, sinh ra từ 10 NADH và 2 FADH₂ qua phosphoryl hoá oxi hoá.',
        'Tổng cộng: khoảng 30-32 ATP cho mỗi phân tử glucose. Các sách cũ ghi 36-38 ATP vì tính tròn mỗi NADH được 3 ATP, còn số đo hiện nay thấp hơn do tế bào phải tốn một phần chênh lệch H⁺ để vận chuyển chất qua màng ti thể.',
      ],
      answer: 'Khoảng 30-32 ATP cho mỗi phân tử glucose (sách cũ ghi 36-38 ATP).',
    },
    checkQuestions: [
      {
        prompt: 'Giai đoạn nào trong hô hấp hiếu khí tạo ra nhiều ATP nhất?',
        choices: [
          { id: 'hr_1', label: 'Chuỗi chuyền điện tử (Electron Transport Chain)' },
          { id: 'hr_2', label: 'Đường phân (Glycolysis)' },
          { id: 'hr_3', label: 'Chu trình Krebs' },
          { id: 'hr_4', label: 'Tất cả giai đoạn đóng góp bằng nhau' },
        ],
        answer: { kind: 'choice', correctIds: ['hr_1'] },
        explain:
          'Chuỗi chuyền điện tử tạo khoảng 26-28 ATP, trong khi đường phân và chu trình Krebs mỗi giai đoạn chỉ thu 2 ATP. Lí do: hai giai đoạn đầu chủ yếu nạp năng lượng vào NADH và FADH₂, phải tới chuỗi chuyền điện tử số năng lượng đó mới được đổi thành ATP.',
      },
      {
        prompt: 'Sản phẩm phụ của quang hợp được thải ra ngoài môi trường là:',
        choices: [
          { id: 'qh_1', label: 'Oxy (O₂)' },
          { id: 'qh_2', label: 'CO₂' },
          { id: 'qh_3', label: 'ATP' },
          { id: 'qh_4', label: 'Glucose' },
        ],
        answer: { kind: 'choice', correctIds: ['qh_1'] },
        explain:
          'O₂ là sản phẩm phụ của pha sáng quang hợp, sinh ra khi H₂O bị phân li bởi năng lượng ánh sáng.',
      },
    ],
    srsCards: [
      {
        hoi: 'Viết phương trình tổng quát của hô hấp tế bào hiếu khí?',
        dap: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Năng lượng (ATP).',
      },
      {
        hoi: 'Quang hợp và hô hấp tế bào là hai quá trình đối nghịch như thế nào?',
        dap: 'Quang hợp: CO₂ + H₂O + ánh sáng → C₆H₁₂O₆ + O₂ (tích luỹ năng lượng). Hô hấp: C₆H₁₂O₆ + O₂ → CO₂ + H₂O + ATP (giải phóng năng lượng).',
      },
    ],
    animation: {
      title: 'Ba giai đoạn của hô hấp tế bào và nơi thu ATP',
      description:
        'Một phân tử glucose đi qua ba chặng. Chặng một, đường phân, diễn ra ở tế bào chất và không cần oxygen: glucose bị cắt thành hai pyruvic acid, thu lãi 2 ATP cùng 2 NADH. Chặng hai, oxi hoá pyruvic acid rồi chu trình Krebs, diễn ra trong chất nền ti thể: carbon bị tách hết thành CO₂, năng lượng phần lớn không ra thẳng ATP mà nạp vào các chất mang NADH và FADH₂, chỉ thu thêm 2 ATP. Chặng ba, chuỗi truyền electron ở màng trong ti thể: NADH và FADH₂ nhả electron, năng lượng được dùng bơm H⁺ tạo chênh lệch nồng độ hai bên màng, H⁺ quay lại qua ATP synthase sinh khoảng 26–28 ATP; oxygen đứng cuối chuỗi nhận electron và kết hợp H⁺ tạo nước. Vì thế thiếu oxygen thì chuỗi tắc, NADH không được tái tạo, và tế bào chỉ còn sống nhờ 2 ATP ít ỏi của đường phân.',
      viewBoxWidth: 460,
      viewBoxHeight: 200,
      durationMs: 9000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'bao1',
          x: 8,
          y: 30,
          w: 136,
          h: 100,
          rx: 10,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'rect',
          id: 'bao2',
          x: 162,
          y: 30,
          w: 136,
          h: 100,
          rx: 10,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'rect',
          id: 'bao3',
          x: 316,
          y: 30,
          w: 136,
          h: 100,
          rx: 10,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'n1',
          x: 76,
          y: 50,
          text: '1. Đường phân',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o1',
          x: 76,
          y: 66,
          text: 'tế bào chất',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 't1',
          x: 76,
          y: 92,
          text: 'glucose → 2 pyruvate',
          size: 11,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'tb1',
          x: 76,
          y: 114,
          text: '2 ATP + 2 NADH',
          size: 11,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'n2',
          x: 230,
          y: 50,
          text: '2. Krebs',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o2',
          x: 230,
          y: 66,
          text: 'chất nền ti thể',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 't2',
          x: 230,
          y: 92,
          text: 'carbon → CO₂',
          size: 11,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'tb2',
          x: 230,
          y: 114,
          text: '2 ATP + NADH, FADH₂',
          size: 11,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'n3',
          x: 384,
          y: 50,
          text: '3. Chuỗi truyền e⁻',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o3',
          x: 384,
          y: 66,
          text: 'màng trong ti thể',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 't3',
          x: 384,
          y: 92,
          text: 'O₂ nhận e⁻ → H₂O',
          size: 11,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'tb3',
          x: 384,
          y: 114,
          text: '≈ 26–28 ATP',
          size: 11,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'arrow',
          id: 'a1',
          x1: 144,
          y1: 80,
          x2: 162,
          y2: 80,
          stroke: 'primary',
          strokeWidth: 3,
          keyframes: [
            { atMs: 0, opacity: 0.2 },
            { atMs: 2000, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'a2',
          x1: 298,
          y1: 80,
          x2: 316,
          y2: 80,
          stroke: 'primary',
          strokeWidth: 3,
          keyframes: [
            { atMs: 0, opacity: 0.2 },
            { atMs: 2000, opacity: 0.2 },
            { atMs: 4500, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'ray',
          x1: 20,
          y1: 150,
          x2: 440,
          y2: 150,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 4',
        },
        {
          kind: 'circle',
          id: 'glu',
          cx: 30,
          cy: 150,
          r: 8,
          fill: 'correct',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 7000, dx: 400 },
            { atMs: 9000, dx: 400, opacity: 0.3 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-tong',
          x: 230,
          y: 184,
          text: 'Tổng: khoảng 30–32 ATP cho mỗi glucose',
          size: 13,
          anchor: 'middle',
          fill: 'primary',
        },
      ],
      captions: [
        { atMs: 0, text: 'Đường phân không cần oxygen, chỉ lãi 2 ATP.' },
        {
          atMs: 3000,
          text: 'Krebs hầu như không sinh ATP trực tiếp — nó nạp năng lượng vào NADH, FADH₂.',
        },
        {
          atMs: 6000,
          text: 'Phần lớn ATP sinh ở chuỗi truyền electron; O₂ là chất nhận electron cuối cùng.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c5-b15',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 15,
    title:
      'Thực hành: Thí nghiệm phân tích ảnh hưởng của một số yếu tố đến hoạt tính của enzyme và kiểm tra hoạt tính của enzyme amylase',
    hook: 'Enzyme hoạt động trong điều kiện nhất định. Nhiệt độ cao có thể biến nước bọt mất khả năng tiêu hoá tinh bột. Hãy kiểm chứng điều này trong phòng thí nghiệm.',
    theory:
      '## Các yếu tố ảnh hưởng đến hoạt tính của enzyme\n' +
      '1. Nhiệt độ:\n' +
      '   — Nhiệt độ thấp: Enzyme hoạt động chậm.\n' +
      '   — Nhiệt độ tối ưu (thường 37-40°C với enzyme người): Hoạt tính cao nhất.\n' +
      '   — Nhiệt độ cao (>60°C): Enzyme bị biến tính (denature), mất hoạt tính vĩnh viễn vì cấu trúc không gian bị phá huỷ.\n' +
      '2. pH:\n' +
      '   — Mỗi enzyme có pH tối ưu khác nhau (amylase nước bọt: pH ~7, pepsin dạ dày: pH ~2).\n' +
      '   — pH quá cao hoặc thấp làm enzyme biến tính.\n' +
      '3. Nồng độ cơ chất: Khi tăng nồng độ cơ chất đến mức bão hoà enzyme, vận tốc phản ứng tăng rồi đạt mức tối đa (Vmax).\n\n' +
      '## Thí nghiệm với amylase nước bọt\n' +
      '— Ống 1 (đối chứng - nhiệt độ phòng): Amylase + hồ tinh bột → thử với dung dịch iốt sau 3 phút: không xanh tím (tinh bột đã bị phân giải).\n' +
      '— Ống 2 (đun sôi): Đun sôi amylase trước rồi thêm hồ tinh bột → thử iốt: xanh tím (tinh bột không bị phân giải, enzyme bị biến tính).\n' +
      '— Ống 3 (môi trường acid): Thêm HCl loãng → thử iốt: xanh tím (pH thấp làm enzyme mất hoạt tính).',
    workedExample: {
      problem:
        'Thiết kế thí nghiệm kiểm tra ảnh hưởng của nhiệt độ lên hoạt tính của enzyme amylase trong nước bọt.',
      steps: [
        'Chuẩn bị 3 ống nghiệm: Ống A (4°C), Ống B (37°C), Ống C (70°C).',
        'Cho vào mỗi ống 2 ml hồ tinh bột 1% và 1 ml nước bọt pha loãng 1:10.',
        'Ủ mỗi ống ở nhiệt độ tương ứng trong 10 phút.',
        'Nhỏ 2 giọt dung dịch iốt vào mỗi ống và quan sát màu sắc. Ống không xanh tím = tinh bột bị phân giải = enzyme hoạt động.',
      ],
      answer:
        'Ống B (37°C) không xanh tím. Ống A và C xanh tím vì enzyme ở 4°C hoạt động yếu, ở 70°C bị biến tính.',
    },
    checkQuestions: [
      {
        prompt:
          'Tại sao enzyme amylase trong nước bọt mất hoàn toàn khả năng phân giải tinh bột khi bị đun sôi?',
        choices: [
          {
            id: 'bd_1',
            label:
              'Nhiệt độ cao phá vỡ cấu trúc không gian ba chiều của enzyme (biến tính protein)',
          },
          { id: 'bd_2', label: 'Nước sôi pha loãng enzyme làm giảm nồng độ' },
          { id: 'bd_3', label: 'Nhiệt độ cao làm tinh bột cứng hơn enzyme không thể tiếp cận' },
          { id: 'bd_4', label: 'Enzyme tan hoàn toàn trong nước sôi' },
        ],
        answer: { kind: 'choice', correctIds: ['bd_1'] },
        explain:
          'Nhiệt độ quá cao phá vỡ liên kết hydrogen và tương tác kị nước duy trì cấu trúc bậc 3 của protein enzyme, làm biến dạng trung tâm hoạt động và mất khả năng xúc tác.',
      },
      {
        prompt: 'Enzyme pepsin trong dạ dày hoạt động tốt nhất ở pH nào?',
        choices: [
          { id: 'ph_1', label: 'pH khoảng 1-2 (acid mạnh)' },
          { id: 'ph_2', label: 'pH khoảng 7 (trung tính)' },
          { id: 'ph_3', label: 'pH khoảng 8-9 (kiềm nhẹ)' },
          { id: 'ph_4', label: 'pH không ảnh hưởng đến pepsin' },
        ],
        answer: { kind: 'choice', correctIds: ['ph_1'] },
        explain:
          'Pepsin là protease của dạ dày, hoạt động trong môi trường acid dạ dày (pH 1-2) do HCl tiết ra.',
      },
    ],
    srsCards: [
      {
        hoi: 'Điều gì xảy ra với enzyme khi nhiệt độ vượt quá nhiệt độ tối ưu?',
        dap: 'Enzyme bị biến tính: cấu trúc không gian bị phá huỷ, trung tâm hoạt động thay đổi, enzyme mất hoạt tính vĩnh viễn.',
      },
      {
        hoi: 'Mỗi enzyme có một pH tối ưu riêng. pH tối ưu của amylase nước bọt là bao nhiêu?',
        dap: 'pH trung tính, khoảng 6,7 - 7,0.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c6-b16',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 16,
    title: 'Chu kì tế bào và nguyên phân',
    hook:
      'Từ một hợp tử duy nhất, sau hơn 40 lần phân chia bạn có được 37 nghìn tỉ tế bào cấu tạo nên cơ thể. ' +
      'Làm thế nào mỗi tế bào con lại nhận được đầy đủ bộ nhiễm sắc thể?',
    theory:
      '## Chu kì tế bào (cell cycle)\n' +
      '— Chu kì tế bào: Chuỗi các sự kiện diễn ra từ khi tế bào được hình thành đến khi nó phân chia tạo ra tế bào con.\n' +
      '— Gồm 2 giai đoạn chính:\n' +
      '  1. Kì trung gian (Interphase): Chiếm phần lớn thời gian. Gồm G₁ (sinh trưởng, tổng hợp protein), S (nhân đôi DNA), G₂ (chuẩn bị phân bào). DNA được nhân đôi trong pha S.\n' +
      '  2. Phân bào (M phase): Gồm nguyên phân (Mitosis) và phân chia tế bào chất (Cytokinesis).\n\n' +
      '## Nguyên phân (mitosis)\n' +
      '— Từ 1 tế bào mẹ (2n) → 2 tế bào con (2n) có bộ NST giống hệt tế bào mẹ.\n' +
      '— Vai trò: Tăng số lượng tế bào (sinh trưởng, sinh sản), tái sinh mô.\n' +
      '— 4 kì phân bào:\n' +
      '  1. Kì đầu (Prophase): NST bắt đầu co xoắn, thoi phân bào hình thành, màng nhân tiêu biến.\n' +
      '  2. Kì giữa (Metaphase): NST co xoắn cực đại và xếp thành một hàng ở mặt phẳng xích đạo tế bào.\n' +
      '  3. Kì sau (Anaphase): Chromatid tách nhau, di chuyển về 2 cực tế bào.\n' +
      '  4. Kì cuối (Telophase): Màng nhân hình thành, NST giãn xoắn, tế bào chất phân chia.\n' +
      '— Kết quả: 1 tế bào mẹ (2n) → 2 tế bào con (2n).',
    workedExample: {
      problem:
        'Một tế bào có 2n=46 NST trải qua 3 lần nguyên phân liên tiếp. Tính số tế bào con và tổng số NST trong các tế bào con.',
      steps: [
        'Số tế bào con = 2^3 = 8 tế bào.',
        'Mỗi tế bào con có 2n = 46 NST (nguyên phân bảo toàn bộ NST).',
        'Tổng số NST = 8 × 46 = 368 NST.',
      ],
      answer: '8 tế bào con, mỗi tế bào có 46 NST, tổng 368 NST.',
    },
    checkQuestions: [
      {
        prompt: 'Trong chu kì tế bào, DNA được nhân đôi ở pha nào của kì trung gian?',
        choices: [
          { id: 'pha_1', label: 'Pha S' },
          { id: 'pha_2', label: 'Pha G₁' },
          { id: 'pha_3', label: 'Pha G₂' },
          { id: 'pha_4', label: 'Kì đầu của nguyên phân' },
        ],
        answer: { kind: 'choice', correctIds: ['pha_1'] },
        explain:
          'Pha S (Synthesis phase) là giai đoạn nhân đôi DNA trong kì trung gian của chu kì tế bào.',
      },
      {
        prompt:
          'Nguyên phân tạo ra bao nhiêu tế bào con từ 1 tế bào mẹ và chúng có bộ NST như thế nào?',
        choices: [
          { id: 'np_1', label: '2 tế bào con có bộ NST 2n bằng tế bào mẹ' },
          { id: 'np_2', label: '4 tế bào con có bộ NST n (đơn bội)' },
          { id: 'np_3', label: '2 tế bào con có bộ NST n (đơn bội)' },
          { id: 'np_4', label: '4 tế bào con có bộ NST 2n' },
        ],
        answer: { kind: 'choice', correctIds: ['np_1'] },
        explain:
          'Nguyên phân tạo 2 tế bào con có bộ NST lưỡng bội (2n) giống hệt tế bào mẹ, đảm bảo sự ổn định bộ gene.',
      },
    ],
    srsCards: [
      {
        hoi: 'Từ 1 tế bào ban đầu qua k lần nguyên phân tạo ra bao nhiêu tế bào con?',
        dap: '2^k tế bào con, mỗi tế bào có bộ NST 2n.',
      },
      {
        hoi: 'Ở kì nào của nguyên phân NST tập trung ở mặt phẳng xích đạo tế bào?',
        dap: 'Kì giữa (Metaphase).',
      },
    ],
    animation: {
      title: 'Nguyên phân: một tế bào mẹ 2n cho hai tế bào con 2n giống hệt',
      description:
        'Tế bào mẹ có 2n = 4, tức hai cặp nhiễm sắc thể tương đồng: một cặp dài, một cặp ngắn, mỗi cặp gồm một chiếc nguồn gốc từ bố và một chiếc từ mẹ (tô hai màu). Mỗi chiếc đã nhân đôi thành nhiễm sắc thể kép gồm hai chromatid chị em dính nhau ở tâm động (chấm nhỏ giữa hai chromatid). Ở kì giữa, toàn bộ nhiễm sắc thể kép xếp thành MỘT hàng duy nhất trên mặt phẳng xích đạo. Sang kì sau, tâm động tách ra, hai chromatid chị em của mỗi nhiễm sắc thể kép tách nhau đi về hai cực đối diện. Kết quả là mỗi tế bào con nhận đủ 4 nhiễm sắc thể đơn, có bộ nhiễm sắc thể 2n giống hệt tế bào mẹ và giống hệt nhau. Đây chính là điểm khác giảm phân: nguyên phân chỉ có MỘT lần phân chia, xếp MỘT hàng, tách chromatid chị em, nên không làm giảm số lượng nhiễm sắc thể và không tạo biến dị tổ hợp.',
      viewBoxWidth: 440,
      viewBoxHeight: 220,
      durationMs: 9000,
      loop: true,
      shapes: [
        {
          kind: 'circle',
          id: 'tbme',
          cx: 220,
          cy: 110,
          r: 86,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 5200, opacity: 1 },
            { atMs: 6200, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'tbcon1',
          cx: 90,
          cy: 110,
          r: 70,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5200, opacity: 0 },
            { atMs: 6200, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'tbcon2',
          cx: 350,
          cy: 110,
          r: 70,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5200, opacity: 0 },
            { atMs: 6200, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'xichdao',
          x1: 220,
          y1: 26,
          x2: 220,
          y2: 194,
          stroke: 'muted',
          strokeWidth: 2,
          dash: '6 4',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 4800, opacity: 1 },
            { atMs: 5600, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-xd',
          x: 220,
          y: 16,
          text: 'mặt phẳng xích đạo — xếp MỘT hàng',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 4800, opacity: 1 },
            { atMs: 5400, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct1a',
          x: 211,
          y: 44,
          w: 8,
          h: 34,
          rx: 4,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: -130 },
            { atMs: 9000, dx: -130 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct1b',
          x: 221,
          y: 44,
          w: 8,
          h: 34,
          rx: 4,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: 130 },
            { atMs: 9000, dx: 130 },
          ],
        },
        {
          kind: 'circle',
          id: 'tam1',
          cx: 220,
          cy: 61,
          r: 4,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 3000, opacity: 1 },
            { atMs: 3400, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct2a',
          x: 211,
          y: 82,
          w: 8,
          h: 34,
          rx: 4,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: -130 },
            { atMs: 9000, dx: -130 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct2b',
          x: 221,
          y: 82,
          w: 8,
          h: 34,
          rx: 4,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: 130 },
            { atMs: 9000, dx: 130 },
          ],
        },
        {
          kind: 'circle',
          id: 'tam2',
          cx: 220,
          cy: 99,
          r: 4,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 3000, opacity: 1 },
            { atMs: 3400, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct3a',
          x: 211,
          y: 124,
          w: 8,
          h: 22,
          rx: 4,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: -130 },
            { atMs: 9000, dx: -130 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct3b',
          x: 221,
          y: 124,
          w: 8,
          h: 22,
          rx: 4,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: 130 },
            { atMs: 9000, dx: 130 },
          ],
        },
        {
          kind: 'circle',
          id: 'tam3',
          cx: 220,
          cy: 135,
          r: 4,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 3000, opacity: 1 },
            { atMs: 3400, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct4a',
          x: 211,
          y: 150,
          w: 8,
          h: 22,
          rx: 4,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: -130 },
            { atMs: 9000, dx: -130 },
          ],
        },
        {
          kind: 'rect',
          id: 'ct4b',
          x: 221,
          y: 150,
          w: 8,
          h: 22,
          rx: 4,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 0 },
            { atMs: 6000, dx: 130 },
            { atMs: 9000, dx: 130 },
          ],
        },
        {
          kind: 'circle',
          id: 'tam4',
          cx: 220,
          cy: 161,
          r: 4,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 3000, opacity: 1 },
            { atMs: 3400, opacity: 0 },
            { atMs: 9000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-con1',
          x: 90,
          y: 208,
          text: 'tế bào con 2n = 4',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6200, opacity: 0 },
            { atMs: 7000, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-con2',
          x: 350,
          y: 208,
          text: 'tế bào con 2n = 4',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6200, opacity: 0 },
            { atMs: 7000, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
      ],
      captions: [
        { atMs: 0, text: 'Kì giữa: nhiễm sắc thể kép xếp thành MỘT hàng trên mặt phẳng xích đạo.' },
        { atMs: 3000, text: 'Kì sau: tâm động tách, hai chromatid CHỊ EM tách nhau về hai cực.' },
        {
          atMs: 7000,
          text: 'Hai tế bào con đều 2n, giống hệt mẹ — vì mỗi cực nhận một chromatid của mỗi NST.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c6-b17',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 17,
    title: 'Giảm phân',
    hook:
      'Giảm phân là "bí quyết" của sinh sản hữu tính — nó tạo ra trứng và tinh trùng với nửa bộ nhiễm sắc thể. ' +
      'Khi hai tế bào đơn bội kết hợp, bộ NST lại trở về đủ số.',
    theory:
      '## Giảm phân (meiosis)\n' +
      '— Mục tiêu: Tạo ra tế bào sinh dục (giao tử) có bộ NST đơn bội (n = một nửa).\n' +
      '— Diễn ra trong các cơ quan sinh dục.\n' +
      '— Gồm 2 lần phân bào liên tiếp:\n\n' +
      '## Giảm phân I (lần phân bào giảm nhiễm)\n' +
      '— Kì đầu I: Hai NST kép trong mỗi cặp tương đồng bắt đôi với nhau (tiếp hợp) và có thể trao đổi đoạn cho nhau (crossing-over). Thoi phân bào hình thành.\n' +
      '— Kì giữa I: Các cặp NST tương đồng xếp ngẫu nhiên ở mặt phẳng xích đạo.\n' +
      '— Kì sau I: Các NST kép tương đồng phân li về 2 cực.\n' +
      '— Kì cuối I: 2 tế bào con với n NST kép.\n\n' +
      '## Giảm phân II (Giống nguyên phân)\n' +
      '— Tách chromatid chị em, tạo 4 tế bào con (n NST đơn).\n' +
      '— Kết quả: Từ 1 tế bào (2n) → 4 tế bào con (n).\n\n' +
      '## Ý nghĩa\n' +
      '— Duy trì bộ NST của loài ổn định qua các thế hệ sinh sản hữu tính.\n' +
      '— Tăng biến dị di truyền (nhờ crossing-over và phân li độc lập các cặp NST tương đồng).',
    workedExample: {
      problem:
        'Một tế bào sinh trứng 2n=46 NST qua giảm phân tạo ra bao nhiêu tế bào trứng? Bộ NST trong mỗi trứng là bao nhiêu?',
      steps: [
        '1 tế bào sinh trứng qua giảm phân tạo 4 tế bào con có bộ NST n = 23.',
        'Tuy nhiên ở người, quá trình tạo trứng (oogenesis) phân chia tế bào chất không đều, tạo 1 trứng chín và 2-3 thể cực (polar body) thoái hoá.',
        'Vậy, 1 tế bào sinh trứng (2n=46) → 1 trứng chức năng (n=23) + 2-3 thể cực.',
      ],
      answer: '1 tế bào sinh trứng (2n=46) tạo ra 1 trứng và 2-3 thể cực, tất cả đều có n=23 NST.',
    },
    checkQuestions: [
      {
        prompt:
          '1 tế bào sinh tinh (2n) qua giảm phân tạo ra bao nhiêu tinh trùng? Mỗi tinh trùng có bộ NST là bao nhiêu?',
        choices: [
          { id: 'gp_1', label: '4 tinh trùng, mỗi tinh trùng có n NST' },
          { id: 'gp_2', label: '2 tinh trùng, mỗi tinh trùng có 2n NST' },
          { id: 'gp_3', label: '4 tinh trùng, mỗi tinh trùng có 2n NST' },
          { id: 'gp_4', label: '1 tinh trùng, có n NST' },
        ],
        answer: { kind: 'choice', correctIds: ['gp_1'] },
        explain:
          'Giảm phân từ 1 tế bào 2n tạo 4 tế bào con n NST. Ở nam giới, tất cả 4 tế bào con đều phát triển thành tinh trùng chức năng.',
      },
      {
        prompt:
          'Sự kiện nào sau đây xảy ra trong kì đầu của giảm phân I mà KHÔNG xảy ra trong kì đầu của nguyên phân?',
        choices: [
          { id: 'co_1', label: 'Trao đổi đoạn (crossing-over) giữa các NST tương đồng' },
          { id: 'co_2', label: 'NST co xoắn cực đại' },
          { id: 'co_3', label: 'Thoi phân bào hình thành' },
          { id: 'co_4', label: 'Màng nhân tan biến' },
        ],
        answer: { kind: 'choice', correctIds: ['co_1'] },
        explain:
          'Crossing-over (trao đổi đoạn giữa các NST tương đồng) là sự kiện đặc trưng của kì đầu giảm phân I, tạo ra tổ hợp gen mới.',
      },
    ],
    srsCards: [
      {
        hoi: 'Kết quả của giảm phân từ 1 tế bào mẹ (2n) là bao nhiêu tế bào con và có bộ NST thế nào?',
        dap: '4 tế bào con có bộ NST đơn bội (n).',
      },
      {
        hoi: 'Trao đổi đoạn (crossing-over) xảy ra ở giai đoạn nào của giảm phân và có ý nghĩa gì?',
        dap: 'Xảy ra ở kì đầu của Giảm phân I. Tạo ra sự tái tổ hợp gen, tăng biến dị di truyền.',
      },
    ],
    animation: {
      title: 'Giảm phân: hai lần phân chia cho bốn tế bào con n',
      description:
        'Tế bào mẹ 2n = 4 gồm hai cặp nhiễm sắc thể tương đồng đã nhân đôi; mỗi nhiễm sắc thể kép là hai chromatid sát nhau, chấm giữa là tâm động. Giảm phân I: các nhiễm sắc thể kép bắt đôi theo từng cặp tương đồng, xếp thành HAI hàng ở mặt phẳng xích đạo; ở kì sau I mỗi nhiễm sắc thể KÉP nguyên vẹn (tâm động chưa tách) đi về một cực, nên số lượng nhiễm sắc thể giảm một nửa. Giảm phân II giống nguyên phân: tâm động tách, chromatid chị em đi về hai cực, cho bốn tế bào con n. Hai điểm hay nhầm với nguyên phân: lần một xếp HAI hàng và tách cặp TƯƠNG ĐỒNG chứ không tách chromatid chị em; hai cặp phân li độc lập với nhau (cặp dài và cặp ngắn chia về hai cực theo hai kiểu khác nhau) nên tạo biến dị tổ hợp.',
      viewBoxWidth: 460,
      viewBoxHeight: 270,
      durationMs: 12000,
      loop: true,
      shapes: [
        {
          kind: 'circle',
          id: 'me',
          cx: 230,
          cy: 92,
          r: 66,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 4800, opacity: 1 },
            { atMs: 5800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'xd1',
          x1: 230,
          y1: 30,
          x2: 230,
          y2: 154,
          stroke: 'muted',
          strokeWidth: 2,
          dash: '6 4',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 4600, opacity: 1 },
            { atMs: 5400, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'tb1',
          cx: 116,
          cy: 92,
          r: 52,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4800, opacity: 0 },
            { atMs: 5800, opacity: 1 },
            { atMs: 7000, opacity: 1 },
            { atMs: 7800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'tb2',
          cx: 346,
          cy: 92,
          r: 52,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4800, opacity: 0 },
            { atMs: 5800, opacity: 1 },
            { atMs: 7000, opacity: 1 },
            { atMs: 7800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'c1',
          cx: 70,
          cy: 210,
          r: 38,
          fill: 'surface',
          stroke: 'correct',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 7800, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'c2',
          cx: 160,
          cy: 210,
          r: 38,
          fill: 'surface',
          stroke: 'correct',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 7800, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'c3',
          cx: 300,
          cy: 210,
          r: 38,
          fill: 'surface',
          stroke: 'correct',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 7800, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'c4',
          cx: 390,
          cy: 210,
          r: 38,
          fill: 'surface',
          stroke: 'correct',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 7800, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'A1a',
          x: 213,
          y: 58,
          w: 7,
          h: 32,
          rx: 3,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: -108, dy: 0 },
            { atMs: 6800, dx: -108, dy: 0 },
            { atMs: 9200, dx: -147, dy: 121 },
            { atMs: 12000, dx: -147, dy: 121 },
          ],
        },
        {
          kind: 'rect',
          id: 'A1b',
          x: 221,
          y: 58,
          w: 7,
          h: 32,
          rx: 3,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: -108, dy: 0 },
            { atMs: 6800, dx: -108, dy: 0 },
            { atMs: 9200, dx: -64, dy: 121 },
            { atMs: 12000, dx: -64, dy: 121 },
          ],
        },
        {
          kind: 'circle',
          id: 'A1t',
          cx: 220.5,
          cy: 74,
          r: 3.5,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, dx: 0, opacity: 1 },
            { atMs: 2600, dx: 0, opacity: 1 },
            { atMs: 4800, dx: -108, opacity: 1 },
            { atMs: 6800, dx: -108, opacity: 1 },
            { atMs: 7200, dx: -108, opacity: 0 },
            { atMs: 12000, dx: -108, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'A2a',
          x: 234,
          y: 58,
          w: 7,
          h: 32,
          rx: 3,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: 108, dy: 0 },
            { atMs: 6800, dx: 108, dy: 0 },
            { atMs: 9200, dx: 62, dy: 121 },
            { atMs: 12000, dx: 62, dy: 121 },
          ],
        },
        {
          kind: 'rect',
          id: 'A2b',
          x: 242,
          y: 58,
          w: 7,
          h: 32,
          rx: 3,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: 108, dy: 0 },
            { atMs: 6800, dx: 108, dy: 0 },
            { atMs: 9200, dx: 144, dy: 121 },
            { atMs: 12000, dx: 144, dy: 121 },
          ],
        },
        {
          kind: 'circle',
          id: 'A2t',
          cx: 241.5,
          cy: 74,
          r: 3.5,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, dx: 0, opacity: 1 },
            { atMs: 2600, dx: 0, opacity: 1 },
            { atMs: 4800, dx: 108, opacity: 1 },
            { atMs: 6800, dx: 108, opacity: 1 },
            { atMs: 7200, dx: 108, opacity: 0 },
            { atMs: 12000, dx: 108, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'B1a',
          x: 213,
          y: 100,
          w: 7,
          h: 20,
          rx: 3,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: -108, dy: 0 },
            { atMs: 6800, dx: -108, dy: 0 },
            { atMs: 9200, dx: -147, dy: 121 },
            { atMs: 12000, dx: -147, dy: 121 },
          ],
        },
        {
          kind: 'rect',
          id: 'B1b',
          x: 221,
          y: 100,
          w: 7,
          h: 20,
          rx: 3,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: -108, dy: 0 },
            { atMs: 6800, dx: -108, dy: 0 },
            { atMs: 9200, dx: -64, dy: 121 },
            { atMs: 12000, dx: -64, dy: 121 },
          ],
        },
        {
          kind: 'circle',
          id: 'B1t',
          cx: 220.5,
          cy: 110,
          r: 3.5,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, dx: 0, opacity: 1 },
            { atMs: 2600, dx: 0, opacity: 1 },
            { atMs: 4800, dx: -108, opacity: 1 },
            { atMs: 6800, dx: -108, opacity: 1 },
            { atMs: 7200, dx: -108, opacity: 0 },
            { atMs: 12000, dx: -108, opacity: 0 },
          ],
        },
        {
          kind: 'rect',
          id: 'B2a',
          x: 234,
          y: 100,
          w: 7,
          h: 20,
          rx: 3,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: 108, dy: 0 },
            { atMs: 6800, dx: 108, dy: 0 },
            { atMs: 9200, dx: 62, dy: 121 },
            { atMs: 12000, dx: 62, dy: 121 },
          ],
        },
        {
          kind: 'rect',
          id: 'B2b',
          x: 242,
          y: 100,
          w: 7,
          h: 20,
          rx: 3,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 2600, dx: 0, dy: 0 },
            { atMs: 4800, dx: 108, dy: 0 },
            { atMs: 6800, dx: 108, dy: 0 },
            { atMs: 9200, dx: 144, dy: 121 },
            { atMs: 12000, dx: 144, dy: 121 },
          ],
        },
        {
          kind: 'circle',
          id: 'B2t',
          cx: 241.5,
          cy: 110,
          r: 3.5,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, dx: 0, opacity: 1 },
            { atMs: 2600, dx: 0, opacity: 1 },
            { atMs: 4800, dx: 108, opacity: 1 },
            { atMs: 6800, dx: 108, opacity: 1 },
            { atMs: 7200, dx: 108, opacity: 0 },
            { atMs: 12000, dx: 108, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lbI',
          x: 230,
          y: 16,
          text: 'Giảm phân I: xếp HAI hàng, tách cặp TƯƠNG ĐỒNG',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 6400, opacity: 1 },
            { atMs: 6800, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lbII',
          x: 230,
          y: 16,
          text: 'Giảm phân II: tâm động tách, chromatid chị em về hai cực',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 6800, opacity: 0 },
            { atMs: 7200, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-2',
          x: 230,
          y: 96,
          text: '2 tế bào n (NST kép)',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5200, opacity: 0 },
            { atMs: 5800, opacity: 1 },
            { atMs: 6800, opacity: 1 },
            { atMs: 7400, opacity: 0 },
            { atMs: 12000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'lb-4n',
          x: 230,
          y: 264,
          text: '4 tế bào con, mỗi tế bào n = 2',
          size: 12,
          anchor: 'middle',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 9800, opacity: 0 },
            { atMs: 10400, opacity: 1 },
            { atMs: 12000, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Kì giữa I: nhiễm sắc thể kép bắt đôi theo cặp tương đồng, xếp thành HAI hàng.',
        },
        {
          atMs: 2600,
          text: 'Kì sau I: cả nhiễm sắc thể KÉP đi về một cực, tâm động chưa tách — bộ NST giảm còn một nửa.',
        },
        { atMs: 6800, text: 'Giảm phân II: tâm động mới tách, chromatid chị em đi về hai cực.' },
        { atMs: 9800, text: 'Kết quả: 4 tế bào con n — khác hẳn nguyên phân cho 2 tế bào 2n.' },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c6-b18',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 18,
    title: 'Thực hành: Làm và quan sát tiêu bản quá trình nguyên phân và giảm phân',
    hook: 'Đỉnh rễ hành tây đang phân chia từng giây. Chúng ta có thể nhuộm và soi để trực tiếp nhìn thấy các NST trong từng kì phân bào.',
    theory:
      '## Quy trình làm tiêu bản quan sát nguyên phân (rễ hành tây)\n' +
      '1. Chuẩn bị: Cắt 1 cm đỉnh rễ hành tây đang mọc (đỉnh rễ có nhiều tế bào đang phân chia tích cực).\n' +
      '2. Cố định mẫu: Ngâm đỉnh rễ trong dung dịch Carnoy (ethanol và acid acetic theo tỉ lệ 3:1) để giữ nguyên hình dạng NST.\n' +
      '3. Làm mềm mô: Ngâm đỉnh rễ trong HCl 1N ở 60 °C khoảng 8-12 phút cho mô rã ra, các tế bào tách rời nhau rồi mới nhuộm bằng carmine hoặc Giemsa để NST bắt màu đỏ hoặc tím.\n' +
      '4. Làm tiêu bản ép: Đặt đỉnh rễ lên lam kính, giọt glycerol + thuốc nhuộm, đậy lamela và ép nhẹ.\n' +
      '5. Quan sát: Tìm kiếm các tế bào đang ở các kì khác nhau của nguyên phân dưới vật kính 40x hoặc 100x.',
    workedExample: {
      problem: 'Tại sao người ta chọn đỉnh rễ hành tây để quan sát nguyên phân?',
      steps: [
        'Đỉnh rễ hành tây là vùng sinh trưởng chứa tế bào phân sinh đỉnh (meristematic cells).',
        'Tế bào ở vùng này có chu kì tế bào ngắn, tốc độ phân chia cao, nên xác suất bắt gặp nhiều tế bào ở các kì phân bào khác nhau rất lớn.',
        'Mẫu dễ thu thập, giá rẻ, không cần phòng thí nghiệm chuyên sâu.',
      ],
      answer:
        'Đỉnh rễ có vùng phân sinh đỉnh với nhiều tế bào phân chia tích cực, dễ quan sát các kì nguyên phân.',
    },
    checkQuestions: [
      {
        prompt:
          'Tại sao trong thí nghiệm quan sát nguyên phân ở rễ hành tây, người ta phải xử lí mẫu với HCl?',
        choices: [
          { id: 'hcl_1', label: 'Để làm mềm mô, phá bỏ thành tế bào và tách rời các tế bào' },
          { id: 'hcl_2', label: 'Để nhuộm màu NST đặc hiệu' },
          { id: 'hcl_3', label: 'Để cố định hình thái và bảo quản mẫu' },
          { id: 'hcl_4', label: 'Để kích thích tế bào phân chia nhanh hơn' },
        ],
        answer: { kind: 'choice', correctIds: ['hcl_1'] },
        explain:
          'HCl loãng ở nhiệt độ cao thuỷ phân chất pectin gắn kết các tế bào thực vật với nhau, làm mô mềm ra nên khi ép các tế bào tách rời và dàn thành một lớp mỏng, nhìn rõ NST.',
      },
      {
        prompt:
          'Ở kì nào của nguyên phân, các NST co xoắn tối đa và nhìn rõ nhất dưới kính hiển vi?',
        choices: [
          { id: 'ki_1', label: 'Kì giữa (Metaphase)' },
          { id: 'ki_2', label: 'Kì đầu (Prophase)' },
          { id: 'ki_3', label: 'Kì sau (Anaphase)' },
          { id: 'ki_4', label: 'Kì cuối (Telophase)' },
        ],
        answer: { kind: 'choice', correctIds: ['ki_1'] },
        explain:
          'Ở kì giữa, NST co xoắn cực đại và nằm gọn trên mặt phẳng xích đạo nên quan sát rõ nhất.',
      },
    ],
    srsCards: [
      {
        hoi: 'Tại sao phải dùng HCl khi làm tiêu bản quan sát nguyên phân ở thực vật?',
        dap: 'Để làm mềm mô: HCl thuỷ phân chất pectin gắn giữa các tế bào, giúp tế bào tách rời và dàn mỏng trên lam kính.',
      },
      {
        hoi: 'Khi quan sát tiêu bản, làm thế nào để nhận biết một tế bào đang ở kì giữa của nguyên phân?',
        dap: 'Thấy các NST kép xếp thành hàng ở mặt phẳng trung tâm (xích đạo) tế bào.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'sinh10-c6-b19',
    animation: {
      title: 'Nuôi cấy mô tế bào thực vật: từ mảnh lá đến cây con',
      description:
        'Sáu ô lần lượt kể lại quy trình nuôi cấy mô, mỗi ô là một bước không thể đảo thứ tự. Lấy mẫu mô còn non, thường là đỉnh sinh trưởng hoặc mảnh lá, vì tế bào ở đó còn khả năng phân chia mạnh. Khử trùng bề mặt mẫu bằng cồn và dung dịch hypochlorite để không một vi khuẩn hay bào tử nấm nào lọt vào môi trường giàu đường. Đặt mẫu lên môi trường dinh dưỡng có hormone: tỉ lệ auxin cao so với cytokinin thì mẫu phản phân hoá thành khối mô sẹo; đổi sang tỉ lệ cytokinin cao thì mô sẹo bật chồi; hạ cytokinin, tăng auxin thì chồi ra rễ thành cây hoàn chỉnh, đưa ra vườn ươm. Cái hình động cho thấy: chỉ cần đổi TỈ LỆ hai hormone là đổi hẳn cơ quan mọc ra, vì mọi tế bào đều mang đủ bộ gene của cây.',
      viewBoxWidth: 538,
      viewBoxHeight: 234,
      durationMs: 7800,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tieu-de',
          x: 269,
          y: 24,
          text: 'Quy trình nhân giống in vitro',
          size: 15,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'rect',
          id: 'o0',
          x: 16,
          y: 40,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 200, opacity: 0 },
            { atMs: 500, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n0',
          x: 91,
          y: 66,
          text: '1. Chọn mẫu mô',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 200, opacity: 0 },
            { atMs: 500, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p0',
          x: 91,
          y: 84,
          text: 'đỉnh sinh trưởng',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 200, opacity: 0 },
            { atMs: 500, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt0',
          x1: 166,
          y1: 70,
          x2: 189,
          y2: 70,
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 850, opacity: 0 },
            { atMs: 1150, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'o1',
          x: 194,
          y: 40,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1300, opacity: 0 },
            { atMs: 1600, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n1',
          x: 269,
          y: 66,
          text: '2. Khử trùng mẫu',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1300, opacity: 0 },
            { atMs: 1600, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p1',
          x: 269,
          y: 84,
          text: 'cồn, hypochlorite',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1300, opacity: 0 },
            { atMs: 1600, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt1',
          x1: 344,
          y1: 70,
          x2: 367,
          y2: 70,
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1950, opacity: 0 },
            { atMs: 2250, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'o2',
          x: 372,
          y: 40,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2400, opacity: 0 },
            { atMs: 2700, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n2',
          x: 447,
          y: 66,
          text: '3. Nuôi trên môi trường',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2400, opacity: 0 },
            { atMs: 2700, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p2',
          x: 447,
          y: 84,
          text: 'có auxin, cytokinin',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2400, opacity: 0 },
            { atMs: 2700, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt2',
          x1: 447,
          y1: 100,
          x2: 91,
          y2: 151,
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3050, opacity: 0 },
            { atMs: 3350, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'o3',
          x: 16,
          y: 156,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3500, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n3',
          x: 91,
          y: 182,
          text: '4. Tạo mô sẹo',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3500, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p3',
          x: 91,
          y: 200,
          text: 'auxin ≈ cytokinin',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3500, opacity: 0 },
            { atMs: 3800, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt3',
          x1: 166,
          y1: 186,
          x2: 189,
          y2: 186,
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4150, opacity: 0 },
            { atMs: 4450, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'o4',
          x: 194,
          y: 156,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4600, opacity: 0 },
            { atMs: 4900, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n4',
          x: 269,
          y: 182,
          text: '5. Tạo chồi rồi rễ',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4600, opacity: 0 },
            { atMs: 4900, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p4',
          x: 269,
          y: 200,
          text: 'đổi tỉ lệ hormone',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4600, opacity: 0 },
            { atMs: 4900, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt4',
          x1: 344,
          y1: 186,
          x2: 367,
          y2: 186,
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5250, opacity: 0 },
            { atMs: 5550, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'o5',
          x: 372,
          y: 156,
          w: 150,
          h: 60,
          rx: 9,
          fill: 'surface',
          stroke: 'accent',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5700, opacity: 0 },
            { atMs: 6000, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n5',
          x: 447,
          y: 182,
          text: '6. Cây con đồng nhất',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5700, opacity: 0 },
            { atMs: 6000, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'p5',
          x: 447,
          y: 200,
          text: 'ra vườn ươm',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 5700, opacity: 0 },
            { atMs: 6000, opacity: 1 },
            { atMs: 7800, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'con-chay',
          cx: 26,
          cy: 50,
          r: 6,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 500, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1350, dx: 0, dy: 0, opacity: 1 },
            { atMs: 1600, dx: 178, dy: 0, opacity: 1 },
            { atMs: 2450, dx: 178, dy: 0, opacity: 1 },
            { atMs: 2700, dx: 356, dy: 0, opacity: 1 },
            { atMs: 3550, dx: 356, dy: 0, opacity: 1 },
            { atMs: 3800, dx: 0, dy: 116, opacity: 1 },
            { atMs: 4650, dx: 0, dy: 116, opacity: 1 },
            { atMs: 4900, dx: 178, dy: 116, opacity: 1 },
            { atMs: 5750, dx: 178, dy: 116, opacity: 1 },
            { atMs: 6000, dx: 356, dy: 116, opacity: 1 },
            { atMs: 7800, dx: 356, dy: 116, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 500,
          text: 'Lấy mô non còn khả năng phân chia mạnh, ví dụ đỉnh sinh trưởng hay mảnh lá.',
        },
        {
          atMs: 1600,
          text: 'Khử trùng bề mặt để nấm và vi khuẩn không lọt vào môi trường giàu đường.',
        },
        { atMs: 2700, text: 'Cấy lên môi trường dinh dưỡng vô trùng có hormone sinh trưởng.' },
        { atMs: 3800, text: 'Auxin cao so với cytokinin: tế bào phản phân hoá thành khối mô sẹo.' },
        { atMs: 4900, text: 'Tăng cytokinin thì bật chồi; sau đó tăng auxin thì chồi ra rễ.' },
        { atMs: 6000, text: 'Được hàng loạt cây con giống hệt cây mẹ, đưa ra vườn ươm.' },
      ],
    },
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 19,
    title: 'Công nghệ tế bào',
    hook: 'Nhờ công nghệ tế bào, các nhà khoa học tạo ra giống cây trồng mới chỉ trong vài tháng, sản xuất kháng thể chữa ung thư và thậm chí nuôi cấy da nhân tạo cho bệnh nhân bỏng.',
    theory:
      '## Công nghệ tế bào (cell technology)\n' +
      '— Là ngành kĩ thuật ứng dụng kiến thức sinh học tế bào để sản xuất các sản phẩm phục vụ con người.\n\n' +
      '## Một số lĩnh vực chính\n' +
      '1. Nuôi cấy mô (Tissue culture / Micropropagation):\n' +
      '   — Nguyên tắc: Dựa trên tính toàn năng của tế bào (mỗi tế bào đều chứa đủ bộ gene và có khả năng phát triển thành cơ thể hoàn chỉnh).\n' +
      '   — Quy trình: Lấy mô thực vật → nuôi cấy trên môi trường dinh dưỡng vô trùng (hormone thực vật) → mô sẹo → cây hoàn chỉnh.\n' +
      '   — Ứng dụng: Nhân giống nhanh cây sạch bệnh, giữ giống quý.\n' +
      '2. Nhân bản vô tính (Cloning):\n' +
      '   — Cừu Dolly (1996): Tế bào tuyến vú của cừu trưởng thành được chuyển nhân vào trứng đã bỏ nhân, kích hoạt phát triển → cừu con có bộ gene giống hệt con cừu cho nhân.\n' +
      '3. Tế bào gốc (Stem cells):\n' +
      '   — Tế bào có khả năng tự phân chia và biệt hoá thành nhiều loại tế bào chuyên biệt.\n' +
      '   — Ứng dụng: Điều trị bệnh về máu, hướng tới tạo mô và cơ quan thay thế trong tương lai.',
    workedExample: {
      problem:
        'Giải thích nguyên lí tính toàn năng của tế bào và ý nghĩa của nó trong công nghệ nuôi cấy mô.',
      steps: [
        'Tính toàn năng (totipotency): Mỗi tế bào sinh dưỡng của cơ thể đa bào chứa bộ gene đầy đủ như tế bào ban đầu (tế bào hợp tử).',
        'Trong điều kiện nuôi cấy thích hợp (đủ dinh dưỡng, hormone), tế bào có thể biểu hiện lại tất cả gene cần thiết và phát triển thành cơ thể hoàn chỉnh.',
        'Ứng dụng: Từ 1 mảnh mô nhỏ của cây quý, ta có thể tạo ra hàng nghìn cây con giống nhau bằng nuôi cấy trong ống nghiệm (in vitro).',
      ],
      answer:
        'Tính toàn năng: mọi tế bào có đủ thông tin di truyền → từ 1 mô nhỏ nuôi cấy thành nhiều cây con có bộ gene đồng nhất.',
    },
    checkQuestions: [
      {
        prompt: 'Nguyên lí sinh học nào là cơ sở của kĩ thuật nuôi cấy mô thực vật?',
        choices: [
          { id: 'tn_1', label: 'Tính toàn năng của tế bào' },
          { id: 'tn_2', label: 'Tính chuyên hoá của tế bào biệt hoá' },
          { id: 'tn_3', label: 'Hiện tượng apoptosis (chết tế bào có lập trình)' },
          { id: 'tn_4', label: 'Sự khuếch tán của hormone qua màng tế bào' },
        ],
        answer: { kind: 'choice', correctIds: ['tn_1'] },
        explain:
          'Tính toàn năng (totipotency) là khả năng phát triển thành cơ thể hoàn chỉnh từ một tế bào đơn lẻ, là cơ sở của kĩ thuật nuôi cấy mô.',
      },
      {
        prompt: 'Cừu Dolly được tạo ra bằng phương pháp nào?',
        choices: [
          { id: 'dl_1', label: 'Chuyển nhân từ tế bào sinh dưỡng vào trứng đã bỏ nhân' },
          { id: 'dl_2', label: 'Thụ tinh trong ống nghiệm' },
          { id: 'dl_3', label: 'Ghép gene từ cừu khác' },
          { id: 'dl_4', label: 'Nuôi cấy tế bào gốc từ phôi thai' },
        ],
        answer: { kind: 'choice', correctIds: ['dl_1'] },
        explain:
          'Dolly được tạo bằng kĩ thuật chuyển nhân tế bào soma (somatic cell nuclear transfer - SCNT): lấy nhân tế bào tuyến vú cừu trưởng thành, chuyển vào trứng đã loại bỏ nhân.',
      },
    ],
    srsCards: [
      {
        hoi: 'Tế bào gốc (stem cell) là gì?',
        dap: 'Tế bào có khả năng tự phân chia và biệt hoá thành nhiều loại tế bào chuyên biệt khác nhau.',
      },
      {
        hoi: 'Nhân bản vô tính tạo ra cá thể như thế nào?',
        dap: 'Chuyển nhân tế bào sinh dưỡng vào trứng đã bỏ nhân, kích hoạt phát triển phôi → cá thể có bộ gene giống hệt cá thể cho nhân.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
